/* Generated by scripts/build.js. Source: src/content/*.js */

/* ===== src/common/projects.js ===== */
/* ===== src/common/projects.js ===== */
// 项目注册表 - 所有后台项目的配置集中在此
// 新增项目时在 PROJECTS 数组中追加配置对象，然后 npm run build

const PROJECTS = [
  {
    id: 'gpt-admin-pre',
    name: 'GPT后台-预发布',
    baseUrl: 'https://gpt-admin-pre.hwzxs.com',
    authPath: '/huayun-ai/admin/auth',
    tenantApiPaths: {
      tenantPage: '/huayun-ai/admin/tenant/page',
      deptList: '/huayun-ai/admin/dept/list',
      userPage: '/huayun-ai/admin/tenant/user/page',
      virtualLogin: '/huayun-ai/admin/tenant/user/virtualLogin',
    },
    cookieKeys: ['HWWAFSESID', 'HWWAFSESTIME'],
    enabledFeatures: ['adminPanel', 'quickLogin'],
    hosts: ['gpt-admin-pre.hwzxs.com', '*.hwzxs.com'],
  },
  {
    id: 'local-test',
    name: '本地测试',
    baseUrl: 'http://localhost:3000',
    authPath: '/api/auth',
    tenantApiPaths: {
      tenantPage: '/api/tenant/page',
      deptList: '/api/dept/list',
      userPage: '/api/user/page',
      virtualLogin: '/api/user/virtualLogin',
    },
    cookieKeys: [],
    enabledFeatures: ['adminPanel', 'quickLogin'],
    hosts: ['localhost', '127.0.0.1'],
  },
];

const DEFAULT_PROJECT_ID = 'gpt-admin-pre';

function getById(id) {
  return PROJECTS.find(p => p.id === id);
}

// 浏览器环境暴露到全局命名空间
if (typeof globalThis !== 'undefined') {
  globalThis.InternalDevToolkit = globalThis.InternalDevToolkit || {};
  globalThis.InternalDevToolkit.projects = {
    PROJECTS,
    DEFAULT_PROJECT_ID,
    getById,
  };
}

// Node.js 环境（scripts/build.js）导出
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PROJECTS, DEFAULT_PROJECT_ID, getById };
}


/* ===== src/common/token.js ===== */
/* 内部开发工具箱 — Token 存储 */
/* 登录成功后返回的 token 持久化到 chrome.storage.local */
(() => {
  'use strict';

  const namespace = (globalThis.InternalDevToolkit = globalThis.InternalDevToolkit || {});

  const KEY_PREFIX = 'adminToken'; // { token: string, updatedAt: number }

  const EMPTY = Object.freeze({ token: '', updatedAt: 0 });

  function hasChromeStorage() {
    return typeof chrome !== 'undefined' && Boolean(chrome.storage?.local);
  }

  function normalize(value = {}) {
    return {
      token: typeof value.token === 'string' ? value.token : '',
      updatedAt: typeof value.updatedAt === 'number' ? value.updatedAt : 0,
    };
  }

  async function getStorageKey() {
    const projectId = await namespace.currentProject.getCurrentProjectId();
    return `${KEY_PREFIX}:${projectId}`;
  }

  async function getToken() {
    if (!hasChromeStorage()) return normalize();
    const key = await getStorageKey();
    return new Promise((resolve) => {
      chrome.storage.local.get(key, (items) => {
        if (chrome.runtime?.lastError) {
          resolve(normalize());
          return;
        }
        resolve(normalize(items[key]));
      });
    });
  }

  async function hasToken() {
    return getToken().then((t) => Boolean(t.token));
  }

  async function saveToken(token) {
    const next = { token: String(token || ''), updatedAt: Date.now() };
    if (!hasChromeStorage()) return next;
    const key = await getStorageKey();
    return new Promise((resolve, reject) => {
      chrome.storage.local.set({ [key]: next }, () => {
        if (chrome.runtime?.lastError) {
          reject(new Error(chrome.runtime.lastError.message));
          return;
        }
        resolve(next);
      });
    });
  }

  async function clearToken() {
    if (!hasChromeStorage()) return;
    const key = await getStorageKey();
    return new Promise((resolve) => {
      chrome.storage.local.remove(key, () => resolve());
    });
  }

  namespace.token = { EMPTY, getToken, hasToken, saveToken, clearToken };
})();


/* ===== src/common/credentials.js ===== */
/* 内部开发工具箱 — 后台登录凭据模块 */
/* 注意：账号密码以明文存储于 chrome.storage.local，仅供公司内部开发自用，
   请勿在公开环境或他人电脑上保存敏感凭据。 */
(() => {
  'use strict';

  const namespace = (globalThis.InternalDevToolkit = globalThis.InternalDevToolkit || {});

  const KEY_PREFIX = 'adminCredentials'; // { account: string, password: string }

  const EMPTY = Object.freeze({ account: '', password: '' });

  function hasChromeStorage() {
    return typeof chrome !== 'undefined' && Boolean(chrome.storage?.local);
  }

  function normalize(value = {}) {
    return {
      account: typeof value.account === 'string' ? value.account : '',
      password: typeof value.password === 'string' ? value.password : '',
    };
  }

  async function getStorageKey() {
    const projectId = await namespace.currentProject.getCurrentProjectId();
    return `${KEY_PREFIX}:${projectId}`;
  }

  async function getCredentials() {
    if (!hasChromeStorage()) return normalize();
    const key = await getStorageKey();
    return new Promise((resolve) => {
      chrome.storage.local.get(key, (items) => {
        if (chrome.runtime?.lastError) {
          resolve(normalize());
          return;
        }
        resolve(normalize(items[key]));
      });
    });
  }

  async function saveCredentials(partial) {
    const next = normalize(partial);
    if (!hasChromeStorage()) return next;
    const key = await getStorageKey();
    return new Promise((resolve, reject) => {
      chrome.storage.local.set({ [key]: next }, () => {
        if (chrome.runtime?.lastError) {
          reject(new Error(chrome.runtime.lastError.message));
          return;
        }
        resolve(next);
      });
    });
  }

  async function clearCredentials() {
    if (!hasChromeStorage()) return;
    const key = await getStorageKey();
    return new Promise((resolve) => {
      chrome.storage.local.remove(key, () => resolve());
    });
  }

  namespace.credentials = { EMPTY, getCredentials, saveCredentials, clearCredentials };
})();


/* ===== src/common/tenant.js ===== */
/* 内部开发工具箱 — 租户/用户/部门接口数据模型与参数封装 */
/* 仅包含纯函数，不发起实际网络请求。 */
(() => {
  'use strict';

  const namespace = (globalThis.InternalDevToolkit = globalThis.InternalDevToolkit || {});

  const DEFAULT_DEPT_SOURCE = Object.freeze({ name: '钉钉', value: 'dingtalk', icon: 'dingtalk' });

  function normalizeUser(value = {}) {
    return {
      id: String(value.id ?? ''),
      userId: String(value.userId ?? ''),
      userName: String(value.username ?? value.userName ?? value.name ?? ''),
      phone: String(value.phone ?? value.mobile ?? value.account ?? ''),
      account: String(value.account ?? ''),
      deptId: String(value.deptId ?? ''),
      deptName: String(value.deptName ?? ''),
      tenantId: String(value.tenantId ?? ''),
      accessKey: String(value.accessKey ?? ''),
      roleName: String(value.roleName ?? '') || (Array.isArray(value.roleNameList) ? value.roleNameList.join('、') : ''),
    };
  }

  function normalizeTenant(value = {}) {
    return {
      tenantId: String(value.tenantId ?? value.id ?? ''),
      tenantName: String(value.tenantName ?? value.name ?? ''),
      domain: String(value.domain ?? ''),
      contactName: String(value.contactName ?? ''),
      contactPhone: String(value.contactPhone ?? ''),
      industry: value.industry ?? '',
    };
  }

  function normalizeDept(value = {}) {
    return {
      deptId: String(value.deptId ?? value.id ?? ''),
      deptName: String(value.deptName ?? value.name ?? ''),
      deptSource: value.deptSource ?? DEFAULT_DEPT_SOURCE,
      children: Array.isArray(value.children) ? value.children : [],
    };
  }

  function buildTenantPageBody({ current = 1, size = 10, keyword = '' }) {
    return {
      current: Number(current) || 1,
      size: Number(size) || 10,
      searchType: ['tenantName', 'contactName', 'contactPhone', 'domain'],
      keyword: String(keyword || ''),
    };
  }

  function buildUserPageBody({ tenantId, deptId = '', deptSource = DEFAULT_DEPT_SOURCE, current = 1, size = 10, keyword = '' }) {
    if (!tenantId) throw new Error('tenantId 不能为空');
    return {
      current: Number(current) || 1,
      size: Number(size) || 10,
      deptId: String(deptId || ''),
      tenantId: String(tenantId),
      deptSource: deptSource || DEFAULT_DEPT_SOURCE,
      keyword: String(keyword || ''),
    };
  }

  function buildDeptListBody({ tenantId }) {
    if (!tenantId) throw new Error('tenantId 不能为空');
    return { tenantId: String(tenantId) };
  }

  function buildQuickLoginBody({ id }) {
    if (!id) throw new Error('id 不能为空');
    return { id: String(id) };
  }

  // 兼容常见响应结构：{ data: { records: [], total: 0 } } 或 { data: { list: [], total: 0 } } 或 { result: { records: [] } }
  function extractPageData(response) {
    if (!response || typeof response !== 'object') return { records: [], total: 0 };
    const payload = response.data ?? response.result ?? response;
    if (!payload || typeof payload !== 'object') return { records: [], total: 0 };
    return {
      records: Array.isArray(payload.records) ? payload.records : Array.isArray(payload.list) ? payload.list : [],
      total: typeof payload.total === 'number' ? payload.total : (Array.isArray(payload.records) ? payload.records.length : 0),
      current: payload.current ?? 1,
      size: payload.size ?? 10,
    };
  }

  function extractListData(response) {
    if (!response || typeof response !== 'object') return [];
    const payload = response.data ?? response.result ?? response;
    return Array.isArray(payload) ? payload : [];
  }

  function extractErrorMessage(response) {
    if (!response || typeof response !== 'object') return '';
    return response.msg || response.message || response.error || response.errorMessage || '';
  }

  function extractToken(response) {
    if (!response || typeof response !== 'object') return '';
    const data = response.data ?? response.result ?? response;
    if (typeof data === 'string') return data;
    return data?.token || data?.accessToken || data?.access_token || data?.authorization || data?.jwt || '';
  }

  namespace.tenant = {
    DEFAULT_DEPT_SOURCE,
    normalizeTenant,
    normalizeUser,
    normalizeDept,
    buildTenantPageBody,
    buildUserPageBody,
    buildDeptListBody,
    buildQuickLoginBody,
    extractPageData,
    extractListData,
    extractErrorMessage,
    extractToken,
  };
})();


/* ===== src/common/mock-storage.js ===== */
/* 内部开发工具箱 — Mock 规则存储 */
/* 按项目命名空间隔离存储 Mock 规则 */
(() => {
  'use strict';

  const ns = globalThis.InternalDevToolkit || (globalThis.InternalDevToolkit = {});
  const KEY_PREFIX = 'mockRules';

  function hasChromeStorage() {
    return typeof chrome !== 'undefined' && Boolean(chrome.storage?.local);
  }

  async function getStorageKey() {
    if (ns.currentProject && ns.currentProject.getCurrentProjectId) {
      const projectId = await ns.currentProject.getCurrentProjectId();
      return `${KEY_PREFIX}:${projectId}`;
    }
    // Fallback: 如果 currentProject 未加载，使用默认
    return `${KEY_PREFIX}:gpt-admin-pre`;
  }

  // 获取当前项目的所有 Mock 规则
  async function getMockRules() {
    if (!hasChromeStorage()) return [];
    const key = await getStorageKey();
    return new Promise((resolve) => {
      chrome.storage.local.get(key, (items) => {
        if (chrome.runtime?.lastError) {
          resolve([]);
          return;
        }
        resolve(Array.isArray(items[key]) ? items[key] : []);
      });
    });
  }

  // 保存单条规则（如果已存在则更新）
  async function saveMockRule(rule) {
    if (!hasChromeStorage()) return;
    const key = await getStorageKey();
    const rules = await getMockRules();

    const existingIndex = rules.findIndex(r => r.id === rule.id);
    if (existingIndex >= 0) {
      rules[existingIndex] = { ...rule, updatedAt: Date.now() };
    } else {
      rules.push({ ...rule, createdAt: Date.now(), updatedAt: Date.now() });
    }

    return new Promise((resolve, reject) => {
      chrome.storage.local.set({ [key]: rules }, () => {
        if (chrome.runtime?.lastError) {
          reject(new Error(chrome.runtime.lastError.message));
          return;
        }
        resolve(rule);
      });
    });
  }

  // 删除规则
  async function deleteMockRule(ruleId) {
    if (!hasChromeStorage()) return;
    const key = await getStorageKey();
    const rules = await getMockRules();
    const filtered = rules.filter(r => r.id !== ruleId);

    return new Promise((resolve, reject) => {
      chrome.storage.local.set({ [key]: filtered }, () => {
        if (chrome.runtime?.lastError) {
          reject(new Error(chrome.runtime.lastError.message));
          return;
        }
        resolve({ ok: true });
      });
    });
  }

  // 启用/禁用规则
  async function toggleMockRule(ruleId, enabled) {
    if (!hasChromeStorage()) return;
    const key = await getStorageKey();
    const rules = await getMockRules();

    const rule = rules.find(r => r.id === ruleId);
    if (!rule) {
      throw new Error('Rule not found');
    }

    rule.enabled = enabled;
    rule.updatedAt = Date.now();

    return new Promise((resolve, reject) => {
      chrome.storage.local.set({ [key]: rules }, () => {
        if (chrome.runtime?.lastError) {
          reject(new Error(chrome.runtime.lastError.message));
          return;
        }
        resolve(rule);
      });
    });
  }

  // 获取指定规则
  async function getMockRule(ruleId) {
    const rules = await getMockRules();
    return rules.find(r => r.id === ruleId);
  }

  ns.mockStorage = {
    getMockRules,
    saveMockRule,
    deleteMockRule,
    toggleMockRule,
    getMockRule,
  };
})();


/* ===== src/common/mock-generator.js ===== */
/* 内部开发工具箱 — Mock 数据生成器 */
/* 从真实数据推断 Schema，智能生成假数据（参考 Faker.js 思路）*/
(() => {
  'use strict';

  const ns = globalThis.InternalDevToolkit || (globalThis.InternalDevToolkit = {});

  // ========== 数据库 ==========

  // 中文姓氏（百家姓前100个）
  const SURNAMES = [
    '王', '李', '张', '刘', '陈', '杨', '黄', '赵', '周', '吴',
    '徐', '孙', '朱', '马', '胡', '郭', '林', '何', '高', '梁',
    '郑', '罗', '宋', '谢', '唐', '韩', '曹', '许', '邓', '萧',
    '冯', '曾', '程', '蔡', '彭', '潘', '袁', '于', '董', '余',
    '苏', '叶', '吕', '魏', '蒋', '田', '杜', '丁', '沈', '姜'
  ];

  // 中文名字
  const GIVEN_NAMES = [
    '伟', '芳', '娜', '秀英', '敏', '静', '丽', '强', '磊', '军',
    '洋', '勇', '艳', '杰', '娟', '涛', '明', '超', '秀兰', '霞',
    '平', '刚', '桂英', '华', '建华', '建国', '秀云', '梅', '英', '雪'
  ];

  // 城市
  const CITIES = [
    '北京市', '上海市', '广州市', '深圳市', '杭州市', '成都市',
    '武汉市', '西安市', '南京市', '重庆市', '天津市', '苏州市',
    '长沙市', '郑州市', '沈阳市', '青岛市', '宁波市', '东莞市'
  ];

  // 街道
  const STREETS = [
    '人民路', '解放路', '建设路', '中山路', '和平路', '新华路',
    '光明路', '胜利路', '朝阳路', '幸福路', '文化路', '友谊路'
  ];

  // 公司类型
  const COMPANY_TYPES = [
    '科技有限公司', '网络科技有限公司', '信息技术有限公司',
    '软件开发有限公司', '电子商务有限公司', '文化传媒有限公司',
    '咨询有限公司', '实业有限公司', '贸易有限公司'
  ];

  // 公司前缀
  const COMPANY_PREFIXES = [
    '阿里', '腾讯', '百度', '华为', '小米', '京东', '美团', '字节',
    '滴滴', '快手', '拼多多', '网易', '新浪', '搜狐', '携程', '去哪儿'
  ];

  // Lorem Ipsum 中文
  const LOREM_WORDS = [
    '的', '是', '在', '了', '和', '有', '我', '他', '不', '人',
    '都', '一', '个', '上', '也', '很', '到', '说', '要', '去',
    '就', '得', '可', '以', '会', '能', '好', '看', '时', '地'
  ];

  // ========== 工具函数 ==========

  function pick(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
  }

  function randomInt(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }

  function randomFloat(min, max, decimals = 2) {
    const num = Math.random() * (max - min) + min;
    return parseFloat(num.toFixed(decimals));
  }

  function randomString(len = 8, chars = 'abcdefghijklmnopqrstuvwxyz0123456789') {
    return Array.from({ length: len }, () => pick(chars.split(''))).join('');
  }

  function randomBoolean() {
    return Math.random() > 0.5;
  }

  // ========== Faker 风格的生成器 ==========

  const faker = {
    // 人名
    person: {
      fullName() {
        return pick(SURNAMES) + pick(GIVEN_NAMES);
      },
      firstName() {
        return pick(GIVEN_NAMES);
      },
      lastName() {
        return pick(SURNAMES);
      },
    },

    // 互联网
    internet: {
      email() {
        const name = randomString(6, 'abcdefghijklmnopqrstuvwxyz');
        const domains = ['example.com', 'test.com', 'demo.com', 'mail.com'];
        return `${name}@${pick(domains)}`;
      },
      userName() {
        return randomString(8, 'abcdefghijklmnopqrstuvwxyz0123456789_');
      },
      password() {
        return randomString(12, 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%');
      },
      url() {
        const protocols = ['http', 'https'];
        const domains = ['example.com', 'test.com', 'demo.com'];
        return `${pick(protocols)}://${pick(domains)}/${randomString(8)}`;
      },
      avatar() {
        return `https://i.pravatar.cc/150?u=${randomString(8)}`;
      },
      ipv4() {
        return `${randomInt(1, 255)}.${randomInt(0, 255)}.${randomInt(0, 255)}.${randomInt(1, 255)}`;
      },
      color() {
        return `#${randomString(6, '0123456789abcdef')}`;
      },
    },

    // 电话
    phone: {
      number() {
        const prefixes = ['130', '131', '132', '133', '134', '135', '136', '137', '138', '139',
                         '150', '151', '152', '153', '155', '156', '157', '158', '159',
                         '180', '181', '182', '183', '184', '185', '186', '187', '188', '189'];
        return pick(prefixes) + Array.from({ length: 8 }, () => randomInt(0, 9)).join('');
      },
    },

    // 地址
    location: {
      city() {
        return pick(CITIES);
      },
      street() {
        return pick(STREETS) + randomInt(1, 999) + '号';
      },
      address() {
        return pick(CITIES) + pick(STREETS) + randomInt(1, 999) + '号';
      },
      zipCode() {
        return Array.from({ length: 6 }, () => randomInt(0, 9)).join('');
      },
      latitude() {
        return randomFloat(-90, 90, 6);
      },
      longitude() {
        return randomFloat(-180, 180, 6);
      },
    },

    // 公司
    company: {
      name() {
        return pick(COMPANY_PREFIXES) + pick(COMPANY_TYPES);
      },
      suffix() {
        return pick(COMPANY_TYPES);
      },
    },

    // 日期时间
    date: {
      past() {
        const now = Date.now();
        const year = 365 * 24 * 60 * 60 * 1000;
        return now - randomInt(0, year);
      },
      future() {
        const now = Date.now();
        const year = 365 * 24 * 60 * 60 * 1000;
        return now + randomInt(0, year);
      },
      recent() {
        const now = Date.now();
        const week = 7 * 24 * 60 * 60 * 1000;
        return now - randomInt(0, week);
      },
      timestamp() {
        return Date.now();
      },
    },

    // 数字
    number: {
      int(min = 0, max = 1000) {
        return randomInt(min, max);
      },
      float(min = 0, max = 1000, decimals = 2) {
        return randomFloat(min, max, decimals);
      },
    },

    // 文本
    lorem: {
      word() {
        return pick(LOREM_WORDS);
      },
      words(count = 3) {
        return Array.from({ length: count }, () => pick(LOREM_WORDS)).join('');
      },
      sentence() {
        const len = randomInt(5, 15);
        return Array.from({ length: len }, () => pick(LOREM_WORDS)).join('') + '。';
      },
      paragraph() {
        const sentences = randomInt(3, 6);
        return Array.from({ length: sentences }, () => faker.lorem.sentence()).join('');
      },
    },

    // 金融
    finance: {
      amount(min = 0, max = 10000, decimals = 2) {
        return randomFloat(min, max, decimals);
      },
      account() {
        return Array.from({ length: 16 }, () => randomInt(0, 9)).join('');
      },
    },

    // 图片
    image: {
      avatar() {
        return faker.internet.avatar();
      },
      url(width = 640, height = 480) {
        return `https://picsum.photos/${width}/${height}?random=${randomInt(1, 1000)}`;
      },
    },

    // UUID
    datatype: {
      uuid() {
        return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
          const r = Math.random() * 16 | 0;
          const v = c === 'x' ? r : (r & 0x3 | 0x8);
          return v.toString(16);
        });
      },
      boolean() {
        return randomBoolean();
      },
    },
  };

  // ========== Schema 推断 ==========

  function inferSchema(data, fieldName = '') {
    if (data === null || data === undefined) {
      return { type: 'null' };
    }

    const type = Array.isArray(data) ? 'array' : typeof data;

    if (type === 'array') {
      const items = data.length > 0 ? inferSchema(data[0], fieldName) : { type: 'any' };
      return { type: 'array', items, length: data.length };
    }

    if (type === 'object') {
      const properties = {};
      for (const key in data) {
        if (data.hasOwnProperty(key)) {
          properties[key] = inferSchema(data[key], key);
        }
      }
      return { type: 'object', properties };
    }

    return { type, fieldName };
  }

  // ========== 启发式生成 ==========

  function generateByFieldName(fieldName, type) {
    const lower = (fieldName || '').toLowerCase();

    // 姓名
    if (/^name$|^username$|^user_?name$|^realname$|^real_?name$/.test(lower)) {
      return faker.person.fullName();
    }
    if (/nickname|nick_?name/.test(lower)) {
      return faker.person.fullName();
    }
    if (/first_?name|given_?name/.test(lower)) {
      return faker.person.firstName();
    }
    if (/last_?name|surname|family_?name/.test(lower)) {
      return faker.person.lastName();
    }

    // 邮箱
    if (/email|mail/.test(lower)) {
      return faker.internet.email();
    }

    // 手机号
    if (/phone|mobile|tel|cellphone/.test(lower)) {
      return faker.phone.number();
    }

    // ID
    if (/^id$|^uid$|user_?id|account_?id|customer_?id/.test(lower)) {
      return faker.number.int(1000, 999999);
    }

    // UUID
    if (/uuid|guid/.test(lower)) {
      return faker.datatype.uuid();
    }

    // URL
    if (/^url$|link|href|website/.test(lower)) {
      return faker.internet.url();
    }

    // 头像/图片
    if (/avatar|photo|image|img|pic|picture/.test(lower)) {
      return faker.internet.avatar();
    }

    // IP
    if (/^ip$|ip_?address|ipv4/.test(lower)) {
      return faker.internet.ipv4();
    }

    // 颜色
    if (/color|colour/.test(lower)) {
      return faker.internet.color();
    }

    // 时间戳
    if (/time|date|timestamp|created_?at|updated_?at|deleted_?at/.test(lower)) {
      return faker.date.timestamp();
    }

    // 地址
    if (/address|addr/.test(lower)) {
      return faker.location.address();
    }
    if (/city/.test(lower)) {
      return faker.location.city();
    }
    if (/street/.test(lower)) {
      return faker.location.street();
    }
    if (/zip|zipcode|postal/.test(lower)) {
      return faker.location.zipCode();
    }

    // 公司
    if (/company|corp|corporation|organization/.test(lower)) {
      return faker.company.name();
    }

    // 金额
    if (/amount|price|cost|fee|balance|total/.test(lower)) {
      return faker.finance.amount();
    }

    // 账号
    if (/account|card_?number|bank_?account/.test(lower)) {
      return faker.finance.account();
    }

    // 密码
    if (/password|pwd|passwd/.test(lower)) {
      return faker.internet.password();
    }

    // 描述/内容
    if (/desc|description|content|comment|remark/.test(lower)) {
      return faker.lorem.sentence();
    }

    // 标题
    if (/title|subject|heading/.test(lower)) {
      return faker.lorem.words(3);
    }

    // 经纬度
    if (/latitude|lat/.test(lower)) {
      return faker.location.latitude();
    }
    if (/longitude|lng|lon/.test(lower)) {
      return faker.location.longitude();
    }

    // 状态
    if (/status|state/.test(lower) && type === 'number') {
      return faker.number.int(0, 2);
    }

    // 布尔值
    if (/is_|has_|can_|should_|enabled|disabled|active|deleted/.test(lower) && type === 'boolean') {
      return faker.datatype.boolean();
    }

    return null;
  }

  // ========== Mock 数据生成 ==========

  function generateMockData(schema) {
    if (!schema || !schema.type) return null;

    // 尝试根据字段名生成
    const byName = generateByFieldName(schema.fieldName, schema.type);
    if (byName !== null) return byName;

    // 按类型生成
    switch (schema.type) {
      case 'string':
        return faker.lorem.words(randomInt(2, 5));

      case 'number':
        return faker.number.int(1, 1000);

      case 'boolean':
        return faker.datatype.boolean();

      case 'array':
        const arrayLen = schema.length || randomInt(1, 5);
        return Array.from({ length: arrayLen }, () => generateMockData(schema.items));

      case 'object':
        const obj = {};
        for (const key in schema.properties) {
          if (schema.properties.hasOwnProperty(key)) {
            const propSchema = schema.properties[key];
            obj[key] = generateMockData({ ...propSchema, fieldName: key });
          }
        }
        return obj;

      case 'null':
        return null;

      default:
        return null;
    }
  }

  // 导出
  ns.mockGenerator = {
    inferSchema,
    generateMockData,
    generateByFieldName,
    faker, // 暴露 faker 对象供高级用户使用
  };
})();


/* ===== src/content/ui.js ===== */
/* 内部开发工具箱 — 页面 UI 注入（轻提示） */
(() => {
  'use strict';

  const ns = globalThis.InternalDevToolkit || (globalThis.InternalDevToolkit = {});

  const TOAST_ID = 'idt-toast';

  function toast(message, { duration = 2200 } = {}) {
    let el = document.getElementById(TOAST_ID);
    if (!el) {
      el = document.createElement('div');
      el.id = TOAST_ID;
      el.className = 'idt-toast';
      document.body.appendChild(el);
    }
    el.textContent = message;
    el.classList.add('idt-toast--show');
    clearTimeout(el._idtTimer);
    el._idtTimer = setTimeout(() => {
      el.classList.remove('idt-toast--show');
    }, duration);
  }

  ns.ui = { toast };
})();


/* ===== src/content/messages.js ===== */
/* 内部开发工具箱 — popup 与 content 之间的消息通信 */
(() => {
  'use strict';

  const ns = globalThis.InternalDevToolkit || (globalThis.InternalDevToolkit = {});

  // popup -> 当前标签页 content script
  function sendToActiveTab(message) {
    return new Promise((resolve, reject) => {
      chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
        const tab = tabs && tabs[0];
        if (!tab || !tab.id) {
          reject(new Error('未找到活动标签页'));
          return;
        }
        chrome.tabs.sendMessage(tab.id, message, (response) => {
          if (chrome.runtime?.lastError) {
            reject(new Error(chrome.runtime.lastError.message));
            return;
          }
          resolve(response);
        });
      });
    });
  }

  // content script -> background
  function sendToBackground(message) {
    return new Promise((resolve, reject) => {
      chrome.runtime.sendMessage(message, (response) => {
        if (chrome.runtime?.lastError) {
          reject(new Error(chrome.runtime.lastError.message));
          return;
        }
        resolve(response);
      });
    });
  }

  // content script 端注册消息处理
  function onMessage(handler) {
    chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
      const result = handler(msg, sender);
      if (result && typeof result.then === 'function') {
        result.then(sendResponse).catch((err) => sendResponse({ ok: false, error: err.message }));
        return true; // 异步响应
      }
      sendResponse(result);
      return false;
    });
  }

  ns.messages = { sendToActiveTab, sendToBackground, onMessage };
})();


/* ===== src/content/mock-interceptor.js ===== */
/* 内部开发工具箱 — Mock 拦截器 */
/* 在 content script（isolated world）中协调：
   - 请求 background 通过 chrome.scripting.executeScript({world:'MAIN'}) 注入 mock-hook.js
     （页面 CSP 会阻止内联 <script> 注入，必须走 scripting API）
   - 接收页面主上下文通过 postMessage 上报的请求记录
   - 与 DevTools Panel / popup 通过 chrome.runtime 消息通信 */
(() => {
  'use strict';

  const ns = globalThis.InternalDevToolkit || (globalThis.InternalDevToolkit = {});

  // 存储 mock 规则和接口记录
  let mockRules = [];
  let requestLog = [];
  const MAX_LOG_SIZE = 100; // 最多保留 100 条记录

  // 初始化
  async function init() {
    console.log('[Mock Interceptor] Initializing in content script...');

    // 1) 先注入 hook，必须在任何 await 之前同步执行。
    //    页面脚本（如 SkyWalking 浏览器监控）会在 document_start 后极早期缓存
    //    window.fetch / window.XMLHttpRequest 的引用并包装；若等 storage 读取完成
    //    再注入，hook 会晚于其缓存，导致页面请求绕过 hook。
    injectPageScript();

    // 2) 接收页面上下文上报的请求记录（hook 注入后即可注册，仍在 document_start）
    window.addEventListener('message', (event) => {
      if (event.source !== window) return;

      if (event.data.type === 'IDT_REQUEST_LOGGED') {
        const record = event.data.record;
        console.log('[Mock Interceptor] Received request from page context:', record.method, record.url);

        // 同一 method+url 只保留最新一条：替换已有记录，避免重复刷屏
        const key = record.key || (record.method + ' ' + record.url);
        const existingIdx = requestLog.findIndex(r => (r.key || (r.method + ' ' + r.url)) === key);
        if (existingIdx >= 0) {
          requestLog[existingIdx] = record;
        } else {
          requestLog.unshift(record);
        }

        // 限制日志大小
        if (requestLog.length > MAX_LOG_SIZE) {
          requestLog = requestLog.slice(0, MAX_LOG_SIZE);
        }

        // 通知 DevTools Panel
        chrome.runtime.sendMessage({
          type: 'REQUEST_LOGGED',
          request: record,
        }).catch((err) => {
          console.log('[Mock Interceptor] Failed to notify DevTools:', err.message);
        });
      }
    });

    // 3) runtime 消息：规则更新 / 日志查询
    chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
      if (msg.type === 'APPLY_MOCK_RULES') {
        mockRules = msg.rules || [];
        console.log('[Mock Interceptor] Updated rules via message:', mockRules.length);
        // 同步到页面上下文
        window.postMessage({
          type: 'IDT_UPDATE_MOCK_RULES',
          rules: mockRules,
        }, '*');
        sendResponse({ ok: true });
        return true;
      }

      if (msg.type === 'GET_REQUEST_LOG') {
        console.log('[Mock Interceptor] GET_REQUEST_LOG requested, returning', requestLog.length, 'records');
        sendResponse({ ok: true, requests: requestLog });
        return true;
      }

      if (msg.type === 'CLEAR_REQUEST_LOG') {
        requestLog = [];
        console.log('[Mock Interceptor] Request log cleared');
        sendResponse({ ok: true });
        return true;
      }
    });

    // 4) 异步加载 mock 规则（不阻塞 hook 安装）
    if (ns.mockStorage) {
      mockRules = await ns.mockStorage.getMockRules();
      console.log('[Mock Interceptor] Loaded', mockRules.length, 'rules from storage');
    }

    // 5) 规则就绪后同步给页面上下文（此时页面脚本的 message 监听器已注册）
    console.log('[Mock Interceptor] Sending initial rules to page context:', mockRules.length);
    window.postMessage({
      type: 'IDT_UPDATE_MOCK_RULES',
      rules: mockRules,
    }, '*');
  }

  // 请求 background 在当前标签页的主上下文注入 mock-hook.js
  // （content script 无 chrome.scripting 权限，需由 background 执行 executeScript）
  function injectPageScript() {
    console.log('[Mock Interceptor] Requesting MAIN-world hook injection...');
    chrome.runtime.sendMessage(
      { type: 'INJECT_MOCK_HOOK' },
      (response) => {
        if (chrome.runtime?.lastError) {
          console.error('[Mock Interceptor] Inject request failed:', chrome.runtime.lastError.message);
          return;
        }
        console.log('[Mock Interceptor] Hook injection response:', response);
      }
    );
  }

  ns.mockInterceptor = {
    init,
  };
})();


/* ===== src/content/api-token.js ===== */
/* 内部开发工具箱 — Content Script Token 注入 */
/* 在目标后台站将 token 暴露到页面，方便页面脚本或开发者直接使用；并提供消息接口。 */
(() => {
  'use strict';

  const ns = globalThis.InternalDevToolkit || (globalThis.InternalDevToolkit = {});

  function isTargetSite() {
    if (!ns.projects || !ns.projects.PROJECTS) return false;
    const allHosts = ns.projects.PROJECTS.flatMap(p => p.hosts);
    return allHosts.some(h => {
      const pattern = h.replace(/^\*\./, ''); // '*.hwzxs.com' -> 'hwzxs.com'
      if (h.startsWith('*.')) {
        // 通配符匹配：hostname 以 pattern 结尾或完全相等
        return location.hostname === pattern || location.hostname.endsWith('.' + pattern);
      } else {
        // 精确匹配
        return location.hostname === h;
      }
    });
  }

  function exposeToken(token) {
    if (!token) return;
    try {
      // 暴露到页面全局，便于页面内调试脚本或业务代码取用
      Object.defineProperty(window, '__ADMIN_TOKEN__', {
        value: token,
        configurable: true,
        writable: true,
      });
      // 同时写入 localStorage，供同域应用读取（key 可按实际项目调整）
      localStorage.setItem('admin-token', token);
    } catch (_) {
      // 某些页面安全策略可能禁止写入 window/localStorage
    }
  }

  async function injectToken() {
    const tokenState = await ns.token.getToken();
    if (tokenState.token) {
      exposeToken(tokenState.token);
      if (ns.ui) {
        ns.ui.toast('Token 已注入页面');
      }
    }
    return tokenState;
  }

  function clearPageToken() {
    try {
      delete window.__ADMIN_TOKEN__;
      localStorage.removeItem('admin-token');
    } catch (_) {}
  }

  ns.apiToken = { isTargetSite, exposeToken, injectToken, clearPageToken };
})();


/* ===== src/content/api-proxy.js ===== */
/* 内部开发工具箱 — Content Script 代理请求 */
/* 在目标页面上下文发 fetch，天然共享浏览器 Cookie，避免 Service Worker 的 401 问题。 */
(() => {
  'use strict';

  const ns = globalThis.InternalDevToolkit || (globalThis.InternalDevToolkit = {});

  const BASE_URL = 'https://gpt-admin-pre.hwzxs.com';

  async function getToken() {
    const tokenState = await ns.token.getToken();
    return tokenState.token || '';
  }

  async function fetchAdminJson(path, body, { referer = `${BASE_URL}/tenant` } = {}) {
    const token = await getToken();
    if (!token) throw new Error('未获取 admin token，请先登录');

    const headers = {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
      Origin: BASE_URL,
      Referer: referer,
    };

    console.log('[内部开发工具箱 CS] 请求:', path, 'body:', body, 'token:', token.slice(0, 8) + '...');

    const res = await fetch(`${BASE_URL}${path}`, {
      method: 'POST',
      credentials: 'include',
      headers,
      body: JSON.stringify(body),
    });

    if (!res.ok) {
      let extra = '';
      try { extra = await res.text(); } catch (_) {}
      throw new Error(`HTTP ${res.status}: ${res.statusText}${extra ? ' | ' + extra.slice(0, 200) : ''}`);
    }

    const text = await res.text();
    try { return text ? JSON.parse(text) : {}; }
    catch (_) { return { _raw: text }; }
  }

  async function fetchTenantPage(opts) {
    const body = ns.tenant.buildTenantPageBody(opts);
    return fetchAdminJson('/huayun-ai/admin/tenant/page', body, { referer: `${BASE_URL}/tenant?rBK=52` });
  }

  async function fetchDeptList(opts) {
    const body = ns.tenant.buildDeptListBody(opts);
    return fetchAdminJson('/huayun-ai/admin/dept/list', body, { referer: `${BASE_URL}/tenant/user?tenantId=${opts.tenantId}&industry=${opts.industry || 1}` });
  }

  async function fetchUserPage(opts) {
    const body = ns.tenant.buildUserPageBody(opts);
    return fetchAdminJson('/huayun-ai/admin/tenant/user/page', body, { referer: `${BASE_URL}/tenant/user?tenantId=${opts.tenantId}&industry=${opts.industry || 1}` });
  }

  async function quickLogin(opts) {
    const body = ns.tenant.buildQuickLoginBody({ id: opts.id });
    return fetchAdminJson('/huayun-ai/admin/tenant/user/virtualLogin', body, { referer: `${BASE_URL}/tenant/user?tenantId=${opts.tenantId}&industry=${opts.industry || 1}` });
  }

  async function openUrl(url) {
    if (!url) throw new Error('缺少 URL');
    window.open(url, '_blank');
    return { opened: true };
  }

  ns.apiProxy = { fetchTenantPage, fetchDeptList, fetchUserPage, quickLogin, openUrl };
})();


/* ===== src/content/index.js ===== */
/* 内部开发工具箱 — Content Script 入口 */
(() => {
  'use strict';

  const ns = globalThis.InternalDevToolkit;

  async function init() {
    // 初始化 Mock 拦截器
    if (ns.mockInterceptor) {
      await ns.mockInterceptor.init();
    }

    // 接收 popup 发来的消息
    ns.messages.onMessage(async (msg) => {
      if (!msg || !msg.type) return { ok: false, error: 'missing type' };
      switch (msg.type) {
        case 'GET_STATUS':
          return { ok: true, url: location.href, title: document.title };

        case 'GET_TOKEN': {
          const tokenState = await ns.token.getToken();
          return { ok: true, token: tokenState.token, updatedAt: tokenState.updatedAt };
        }

        case 'INJECT_TOKEN': {
          if (!ns.apiToken) return { ok: false, error: 'apiToken 模块未加载' };
          const tokenState = await ns.apiToken.injectToken();
          return { ok: true, token: tokenState.token };
        }

        case 'FETCH_TENANTS_CS': {
          if (!ns.apiProxy) return { ok: false, error: 'apiProxy 模块未加载' };
          const res = await ns.apiProxy.fetchTenantPage(msg.payload);
          return { ok: true, res };
        }

        case 'FETCH_DEPTS_CS': {
          if (!ns.apiProxy) return { ok: false, error: 'apiProxy 模块未加载' };
          const res = await ns.apiProxy.fetchDeptList(msg.payload);
          return { ok: true, res };
        }

        case 'FETCH_USERS_CS': {
          if (!ns.apiProxy) return { ok: false, error: 'apiProxy 模块未加载' };
          const res = await ns.apiProxy.fetchUserPage(msg.payload);
          return { ok: true, res };
        }

        case 'QUICK_LOGIN_CS': {
          if (!ns.apiProxy) return { ok: false, error: 'apiProxy 模块未加载' };
          const res = await ns.apiProxy.quickLogin(msg.payload);
          return { ok: true, res };
        }

        case 'OPEN_URL_CS': {
          if (!ns.apiProxy) return { ok: false, error: 'apiProxy 模块未加载' };
          const result = await ns.apiProxy.openUrl(msg.payload.url);
          return { ok: true, ...result };
        }

        case 'CLEAR_TOKEN': {
          await ns.token.clearToken();
          if (ns.apiToken) ns.apiToken.clearPageToken();
          return { ok: true };
        }

        default:
          return { ok: false, error: `unknown type: ${msg.type}` };
      }
    });

    // 目标后台站：若已保存 token，则自动注入页面
    if (ns.apiToken) {
      setTimeout(() => ns.apiToken.injectToken().catch(() => {}), 400);
    }
  }

  init().catch((err) => {
    console.warn('[内部开发工具箱] 初始化失败:', err);
  });
})();
