/* Generated by scripts/build.js. Source: src/popup/*.js */

/* ===== src/common/projects.js ===== */
/* ===== src/common/projects.js ===== */
// 项目注册表 - 所有后台项目的配置集中在此
// 新增项目时在 PROJECTS 数组中追加配置对象，然后 npm run build

const PROJECTS = [
  {
    id: 'gpt-admin-pre',
    name: 'GPT后台-预发布',
    baseUrl: 'https://gpt-admin-pre.hwzxs.com',
    authPath: '/huayun-ai/admin/auth',
    tenantApiPaths: {
      tenantPage: '/huayun-ai/admin/tenant/page',
      deptList: '/huayun-ai/admin/dept/list',
      userPage: '/huayun-ai/admin/tenant/user/page',
      virtualLogin: '/huayun-ai/admin/tenant/user/virtualLogin',
    },
    cookieKeys: ['HWWAFSESID', 'HWWAFSESTIME'],
    enabledFeatures: ['adminPanel', 'quickLogin'],
    hosts: ['gpt-admin-pre.hwzxs.com', '*.hwzxs.com'],
  },
  {
    id: 'local-test',
    name: '生产',
    baseUrl: 'https://ai-admin.huayuntiantu.com',
    authPath: '/api/auth',
    tenantApiPaths: {
      tenantPage: '/api/tenant/page',
      deptList: '/api/dept/list',
      userPage: '/api/user/page',
      virtualLogin: '/api/user/virtualLogin',
    },
    cookieKeys: [],
    enabledFeatures: ['adminPanel', 'quickLogin'],
    hosts: ['ai-admin.huayuntiantu.com', '*.huayuntiantu.com'],
  },
];

const DEFAULT_PROJECT_ID = 'gpt-admin-pre';

function getById(id) {
  return PROJECTS.find(p => p.id === id);
}

// 浏览器环境暴露到全局命名空间
if (typeof globalThis !== 'undefined') {
  globalThis.InternalDevToolkit = globalThis.InternalDevToolkit || {};
  globalThis.InternalDevToolkit.projects = {
    PROJECTS,
    DEFAULT_PROJECT_ID,
    getById,
  };
}

// Node.js 环境（scripts/build.js）导出
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PROJECTS, DEFAULT_PROJECT_ID, getById };
}


/* ===== src/common/current-project.js ===== */
/* ===== src/common/current-project.js ===== */
// 当前激活项目管理：chrome.storage 读写 + 缓存 + 数据迁移

(function() {
  const ns = globalThis.InternalDevToolkit;
  const STORAGE_KEY = 'currentProjectId';
  let cachedProjectId = null;
  let cachedProject = null;

  async function getCurrentProjectId() {
    const result = await chrome.storage.local.get(STORAGE_KEY);
    return result[STORAGE_KEY] || ns.projects.DEFAULT_PROJECT_ID;
  }

  async function setCurrentProjectId(id) {
    await chrome.storage.local.set({ [STORAGE_KEY]: id });
    cachedProjectId = id;
    cachedProject = ns.projects.getById(id);
  }

  async function loadCurrentProject() {
    cachedProjectId = await getCurrentProjectId();
    cachedProject = ns.projects.getById(cachedProjectId);
    // 同步加载自定义域名覆盖到内存缓存，供 getBaseUrl() 同步读取
    if (ns.customDomain) {
      await ns.customDomain.loadCachedOverride();
    }
    return cachedProject;
  }

  function getCachedProjectId() {
    return cachedProjectId || ns.projects.DEFAULT_PROJECT_ID;
  }

  function getProject() {
    return cachedProject || ns.projects.getById(ns.projects.DEFAULT_PROJECT_ID);
  }

  // 优先返回自定义域名覆盖，否则回落到项目配置的 baseUrl
  function getBaseUrl() {
    if (ns.customDomain) {
      const override = ns.customDomain.getCachedOverride();
      if (override) return override;
    }
    return getProject().baseUrl;
  }

  // 跨上下文刷新内存缓存（popup 保存后通知 background 调用）
  async function refreshBaseUrlCache() {
    if (ns.customDomain) {
      return ns.customDomain.loadCachedOverride();
    }
    return '';
  }

  function getAuthPath() {
    return getProject().authPath;
  }

  function getTenantApiPaths() {
    return getProject().tenantApiPaths;
  }

  function getCookieKeys() {
    return getProject().cookieKeys;
  }

  function getEnabledFeatures() {
    return getProject().enabledFeatures;
  }

  function getName() {
    return getProject().name;
  }

  function getHosts() {
    return getProject().hosts;
  }

  // 数据迁移：将旧版本无项目前缀的 key 迁移到默认项目命名空间
  async function migrateOldStorageKeys() {
    const OLD_KEYS = ['adminToken', 'adminCredentials', 'quickLoginRecent'];
    const result = await chrome.storage.local.get(OLD_KEYS);

    if (!result.adminToken && !result.adminCredentials && !result.quickLoginRecent) {
      return; // 无旧数据，跳过
    }

    const defaultId = ns.projects.DEFAULT_PROJECT_ID;
    const newKeys = {};

    if (result.adminToken) {
      newKeys[`adminToken:${defaultId}`] = result.adminToken;
    }

    if (result.adminCredentials) {
      newKeys[`adminCredentials:${defaultId}`] = result.adminCredentials;
    }

    if (result.quickLoginRecent) {
      newKeys[`quickLoginRecent:${defaultId}`] = result.quickLoginRecent.map(r => ({
        ...r,
        projectId: defaultId
      }));
    }

    await chrome.storage.local.set(newKeys);
    await chrome.storage.local.remove(OLD_KEYS);
    console.log('[Migrate] Moved old storage to project:', defaultId);
  }

  ns.currentProject = {
    getCurrentProjectId,
    setCurrentProjectId,
    loadCurrentProject,
    getCachedProjectId,
    getProject,
    getBaseUrl,
    getAuthPath,
    getTenantApiPaths,
    getCookieKeys,
    getEnabledFeatures,
    getName,
    getHosts,
    migrateOldStorageKeys,
    refreshBaseUrlCache,
  };
})();


/* ===== src/common/credentials.js ===== */
/* 内部开发工具箱 — 后台登录凭据模块 */
/* 注意：账号密码以明文存储于 chrome.storage.local，仅供公司内部开发自用，
   请勿在公开环境或他人电脑上保存敏感凭据。 */
(() => {
  'use strict';

  const namespace = (globalThis.InternalDevToolkit = globalThis.InternalDevToolkit || {});

  const KEY_PREFIX = 'adminCredentials'; // { account: string, password: string }

  const EMPTY = Object.freeze({ account: '', password: '' });

  function hasChromeStorage() {
    return typeof chrome !== 'undefined' && Boolean(chrome.storage?.local);
  }

  function normalize(value = {}) {
    return {
      account: typeof value.account === 'string' ? value.account : '',
      password: typeof value.password === 'string' ? value.password : '',
    };
  }

  async function getStorageKey() {
    const projectId = await namespace.currentProject.getCurrentProjectId();
    return `${KEY_PREFIX}:${projectId}`;
  }

  async function getCredentials() {
    if (!hasChromeStorage()) return normalize();
    const key = await getStorageKey();
    return new Promise((resolve) => {
      chrome.storage.local.get(key, (items) => {
        if (chrome.runtime?.lastError) {
          resolve(normalize());
          return;
        }
        resolve(normalize(items[key]));
      });
    });
  }

  async function saveCredentials(partial) {
    const next = normalize(partial);
    if (!hasChromeStorage()) return next;
    const key = await getStorageKey();
    return new Promise((resolve, reject) => {
      chrome.storage.local.set({ [key]: next }, () => {
        if (chrome.runtime?.lastError) {
          reject(new Error(chrome.runtime.lastError.message));
          return;
        }
        resolve(next);
      });
    });
  }

  async function clearCredentials() {
    if (!hasChromeStorage()) return;
    const key = await getStorageKey();
    return new Promise((resolve) => {
      chrome.storage.local.remove(key, () => resolve());
    });
  }

  namespace.credentials = { EMPTY, getCredentials, saveCredentials, clearCredentials };
})();


/* ===== src/common/token.js ===== */
/* 内部开发工具箱 — Token 存储 */
/* 登录成功后返回的 token 持久化到 chrome.storage.local */
(() => {
  'use strict';

  const namespace = (globalThis.InternalDevToolkit = globalThis.InternalDevToolkit || {});

  const KEY_PREFIX = 'adminToken'; // { token: string, updatedAt: number }

  const EMPTY = Object.freeze({ token: '', updatedAt: 0 });

  function hasChromeStorage() {
    return typeof chrome !== 'undefined' && Boolean(chrome.storage?.local);
  }

  function normalize(value = {}) {
    return {
      token: typeof value.token === 'string' ? value.token : '',
      updatedAt: typeof value.updatedAt === 'number' ? value.updatedAt : 0,
    };
  }

  async function getStorageKey() {
    const projectId = await namespace.currentProject.getCurrentProjectId();
    return `${KEY_PREFIX}:${projectId}`;
  }

  async function getToken() {
    if (!hasChromeStorage()) return normalize();
    const key = await getStorageKey();
    return new Promise((resolve) => {
      chrome.storage.local.get(key, (items) => {
        if (chrome.runtime?.lastError) {
          resolve(normalize());
          return;
        }
        resolve(normalize(items[key]));
      });
    });
  }

  async function hasToken() {
    return getToken().then((t) => Boolean(t.token));
  }

  async function saveToken(token) {
    const next = { token: String(token || ''), updatedAt: Date.now() };
    if (!hasChromeStorage()) return next;
    const key = await getStorageKey();
    return new Promise((resolve, reject) => {
      chrome.storage.local.set({ [key]: next }, () => {
        if (chrome.runtime?.lastError) {
          reject(new Error(chrome.runtime.lastError.message));
          return;
        }
        resolve(next);
      });
    });
  }

  async function clearToken() {
    if (!hasChromeStorage()) return;
    const key = await getStorageKey();
    return new Promise((resolve) => {
      chrome.storage.local.remove(key, () => resolve());
    });
  }

  namespace.token = { EMPTY, getToken, hasToken, saveToken, clearToken };
})();


/* ===== src/common/custom-domain.js ===== */
/* 内部开发工具箱 — 自定义域名（baseUrl）覆盖存储 */
/* 允许在 popup 手动修改当前项目的后端域名，覆盖 PROJECTS 中的默认 baseUrl。
   命名空间键 customBaseUrl:${projectId}，结构与 token 模块一致。 */
(() => {
  'use strict';

  const namespace = (globalThis.InternalDevToolkit = globalThis.InternalDevToolkit || {});

  const KEY_PREFIX = 'customBaseUrl'; // { baseUrl: string, updatedAt: number }

  const EMPTY = Object.freeze({ baseUrl: '', updatedAt: 0 });

  // 内存缓存：避免每次 getBaseUrl() 都异步读 storage（getBaseUrl 是同步 API）
  let cachedOverride = '';

  function hasChromeStorage() {
    return typeof chrome !== 'undefined' && Boolean(chrome.storage?.local);
  }

  function normalize(value = {}) {
    return {
      baseUrl: typeof value.baseUrl === 'string' ? value.baseUrl : '',
      updatedAt: typeof value.updatedAt === 'number' ? value.updatedAt : 0,
    };
  }

  async function getStorageKey() {
    const projectId = await namespace.currentProject.getCurrentProjectId();
    return `${KEY_PREFIX}:${projectId}`;
  }

  async function getDomain() {
    if (!hasChromeStorage()) return normalize();
    const key = await getStorageKey();
    return new Promise((resolve) => {
      chrome.storage.local.get(key, (items) => {
        if (chrome.runtime?.lastError) {
          resolve(normalize());
          return;
        }
        resolve(normalize(items[key]));
      });
    });
  }

  async function hasDomain() {
    return getDomain().then((d) => Boolean(d.baseUrl));
  }

  async function saveDomain(baseUrl) {
    const next = { baseUrl: String(baseUrl || '').trim(), updatedAt: Date.now() };
    cachedOverride = next.baseUrl;
    if (!hasChromeStorage()) return next;
    const key = await getStorageKey();
    return new Promise((resolve, reject) => {
      chrome.storage.local.set({ [key]: next }, () => {
        if (chrome.runtime?.lastError) {
          reject(new Error(chrome.runtime.lastError.message));
          return;
        }
        resolve(next);
      });
    });
  }

  async function clearDomain() {
    cachedOverride = '';
    if (!hasChromeStorage()) return;
    const key = await getStorageKey();
    return new Promise((resolve) => {
      chrome.storage.local.remove(key, () => resolve());
    });
  }

  // 从 storage 载入到内存缓存（loadCurrentProject 时调用）
  async function loadCachedOverride() {
    const state = await getDomain();
    cachedOverride = state.baseUrl || '';
    return cachedOverride;
  }

  // 同步读取缓存的覆盖值（供 getBaseUrl 同步路径使用）
  function getCachedOverride() {
    return cachedOverride;
  }

  // 直接设置内存缓存（跨上下文刷新时使用，无需落盘）
  function setCachedOverride(baseUrl) {
    cachedOverride = typeof baseUrl === 'string' ? baseUrl : '';
  }

  namespace.customDomain = {
    EMPTY,
    getDomain,
    hasDomain,
    saveDomain,
    clearDomain,
    loadCachedOverride,
    getCachedOverride,
    setCachedOverride,
  };
})();


/* ===== src/common/tenant.js ===== */
/* 内部开发工具箱 — 租户/用户/部门接口数据模型与参数封装 */
/* 仅包含纯函数，不发起实际网络请求。 */
(() => {
  'use strict';

  const namespace = (globalThis.InternalDevToolkit = globalThis.InternalDevToolkit || {});

  const DEFAULT_DEPT_SOURCE = Object.freeze({ name: '钉钉', value: 'dingtalk', icon: 'dingtalk' });

  function normalizeUser(value = {}) {
    return {
      id: String(value.id ?? ''),
      userId: String(value.userId ?? ''),
      userName: String(value.username ?? value.userName ?? value.name ?? ''),
      phone: String(value.phone ?? value.mobile ?? value.account ?? ''),
      account: String(value.account ?? ''),
      deptId: String(value.deptId ?? ''),
      deptName: String(value.deptName ?? ''),
      tenantId: String(value.tenantId ?? ''),
      accessKey: String(value.accessKey ?? ''),
      roleName: String(value.roleName ?? '') || (Array.isArray(value.roleNameList) ? value.roleNameList.join('、') : ''),
    };
  }

  function normalizeTenant(value = {}) {
    return {
      tenantId: String(value.tenantId ?? value.id ?? ''),
      tenantName: String(value.tenantName ?? value.name ?? ''),
      domain: String(value.domain ?? ''),
      contactName: String(value.contactName ?? ''),
      contactPhone: String(value.contactPhone ?? ''),
      industry: value.industry ?? '',
    };
  }

  function normalizeDept(value = {}) {
    return {
      deptId: String(value.deptId ?? value.id ?? ''),
      deptName: String(value.deptName ?? value.name ?? ''),
      deptSource: value.deptSource ?? DEFAULT_DEPT_SOURCE,
      children: Array.isArray(value.children) ? value.children : [],
    };
  }

  function buildTenantPageBody({ current = 1, size = 10, keyword = '' }) {
    return {
      current: Number(current) || 1,
      size: Number(size) || 10,
      searchType: ['tenantName', 'contactName', 'contactPhone', 'domain'],
      keyword: String(keyword || ''),
    };
  }

  function buildUserPageBody({ tenantId, deptId = '', deptSource = DEFAULT_DEPT_SOURCE, current = 1, size = 10, keyword = '' }) {
    if (!tenantId) throw new Error('tenantId 不能为空');
    return {
      current: Number(current) || 1,
      size: Number(size) || 10,
      deptId: String(deptId || ''),
      tenantId: String(tenantId),
      deptSource: deptSource || DEFAULT_DEPT_SOURCE,
      keyword: String(keyword || ''),
    };
  }

  function buildDeptListBody({ tenantId }) {
    if (!tenantId) throw new Error('tenantId 不能为空');
    return { tenantId: String(tenantId) };
  }

  function buildQuickLoginBody({ id }) {
    if (!id) throw new Error('id 不能为空');
    return { id: String(id) };
  }

  // 兼容常见响应结构：{ data: { records: [], total: 0 } } 或 { data: { list: [], total: 0 } } 或 { result: { records: [] } }
  function extractPageData(response) {
    if (!response || typeof response !== 'object') return { records: [], total: 0 };
    const payload = response.data ?? response.result ?? response;
    if (!payload || typeof payload !== 'object') return { records: [], total: 0 };
    return {
      records: Array.isArray(payload.records) ? payload.records : Array.isArray(payload.list) ? payload.list : [],
      total: typeof payload.total === 'number' ? payload.total : (Array.isArray(payload.records) ? payload.records.length : 0),
      current: payload.current ?? 1,
      size: payload.size ?? 10,
    };
  }

  function extractListData(response) {
    if (!response || typeof response !== 'object') return [];
    const payload = response.data ?? response.result ?? response;
    return Array.isArray(payload) ? payload : [];
  }

  function extractErrorMessage(response) {
    if (!response || typeof response !== 'object') return '';
    return response.msg || response.message || response.error || response.errorMessage || '';
  }

  function extractToken(response) {
    if (!response || typeof response !== 'object') return '';
    const data = response.data ?? response.result ?? response;
    if (typeof data === 'string') return data;
    return data?.token || data?.accessToken || data?.access_token || data?.authorization || data?.jwt || '';
  }

  namespace.tenant = {
    DEFAULT_DEPT_SOURCE,
    normalizeTenant,
    normalizeUser,
    normalizeDept,
    buildTenantPageBody,
    buildUserPageBody,
    buildDeptListBody,
    buildQuickLoginBody,
    extractPageData,
    extractListData,
    extractErrorMessage,
    extractToken,
  };
})();


/* ===== src/content/messages.js ===== */
/* 内部开发工具箱 — popup 与 content 之间的消息通信 */
(() => {
  'use strict';

  const ns = globalThis.InternalDevToolkit || (globalThis.InternalDevToolkit = {});

  // popup -> 当前标签页 content script
  function sendToActiveTab(message) {
    return new Promise((resolve, reject) => {
      chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
        const tab = tabs && tabs[0];
        if (!tab || !tab.id) {
          reject(new Error('未找到活动标签页'));
          return;
        }
        chrome.tabs.sendMessage(tab.id, message, (response) => {
          if (chrome.runtime?.lastError) {
            reject(new Error(chrome.runtime.lastError.message));
            return;
          }
          resolve(response);
        });
      });
    });
  }

  // content script -> background
  function sendToBackground(message) {
    return new Promise((resolve, reject) => {
      chrome.runtime.sendMessage(message, (response) => {
        if (chrome.runtime?.lastError) {
          reject(new Error(chrome.runtime.lastError.message));
          return;
        }
        resolve(response);
      });
    });
  }

  // content script 端注册消息处理
  function onMessage(handler) {
    chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
      const result = handler(msg, sender);
      if (result && typeof result.then === 'function') {
        result.then(sendResponse).catch((err) => sendResponse({ ok: false, error: err.message }));
        return true; // 异步响应
      }
      sendResponse(result);
      return false;
    });
  }

  ns.messages = { sendToActiveTab, sendToBackground, onMessage };
})();


/* ===== src/popup/ui.js ===== */
/* 内部开发工具箱 — Popup 通用 UI：统一悬浮提示（toast） */
(() => {
  'use strict';

  const ns = globalThis.InternalDevToolkit || (globalThis.InternalDevToolkit = {});

  const TOAST_ID = 'globalToast';
  let hideTimer = 0;
  // ok 类提示自动消失；info / err 保持到下一次调用覆盖或清空
  const OK_AUTO_HIDE_MS = 1800;

  function toast(text, kind) {
    const el = document.getElementById(TOAST_ID);
    if (!el) return;
    clearTimeout(hideTimer);

    const t = text == null ? '' : String(text);
    if (!t) {
      el.classList.remove('show', 'ok', 'err');
      el.textContent = '';
      return;
    }

    el.textContent = t;
    el.classList.remove('ok', 'err');
    if (kind === 'ok' || kind === 'err') el.classList.add(kind);
    el.classList.add('show');

    if (kind === 'ok') {
      hideTimer = setTimeout(() => {
        el.classList.remove('show', 'ok', 'err');
        el.textContent = '';
      }, OK_AUTO_HIDE_MS);
    }
  }

  ns.ui = { toast };
})();


/* ===== src/popup/project-switcher-ui.js ===== */
/* ===== src/popup/project-switcher-ui.js ===== */
// 项目切换器 UI：顶部 pill 导航

(function() {
  const ns = globalThis.InternalDevToolkit;

  async function init() {
    const currentId = await ns.currentProject.getCurrentProjectId();
    const pillsContainer = document.getElementById('projectPills');
    if (!pillsContainer) {
      console.warn('[项目切换器] #projectPills 容器不存在');
      return;
    }

    const pills = ns.projects.PROJECTS.map(p => {
      const isActive = p.id === currentId;
      return `<div class="project-pill ${isActive ? 'active' : ''}" data-project-id="${p.id}">${p.name}</div>`;
    }).join('');

    pillsContainer.innerHTML = pills;

    // 点击切换项目
    pillsContainer.addEventListener('click', async (e) => {
      const pill = e.target.closest('.project-pill');
      if (!pill || pill.classList.contains('active')) return;

      const newId = pill.dataset.projectId;
      await ns.currentProject.setCurrentProjectId(newId);
      await ns.currentProject.loadCurrentProject();

      // 刷新 popup（简单粗暴但有效）
      location.reload();
    });
  }

  ns.projectSwitcherUi = { init };
})();


/* ===== src/popup/quick-login-ui.js ===== */
/* 内部开发工具箱 — Popup 快捷登录 UI */
(() => {
  'use strict';

  const ns = globalThis.InternalDevToolkit;
  const tenantHelpers = ns.tenant;
  const messages = ns.messages;

  const IDs = {
    section: 'quickLoginSection',
    header: 'quickLoginHeader',
    body: 'quickLoginBody',
    envBadge: 'envBadge',
    localPort: 'localPort',
    tenantSearch: 'tenantSearch',
    tenantList: 'tenantList',
    tenantEmpty: 'tenantEmpty',
    deptSelect: 'deptSelect',
    userSearch: 'userSearch',
    userList: 'userList',
    userEmpty: 'userEmpty',
    loadMore: 'loadMoreUsers',
    recent: 'recentList',
  };

  // SVG icons
  const icons = {
    open: '<svg class="icon-svg" viewBox="0 0 24 24"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/></svg>',
    copy: '<svg class="icon-svg" viewBox="0 0 24 24"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>',
    student: '<svg class="icon-svg" viewBox="0 0 24 24"><path d="M22 10v6M2 10l10-5 10 5-10 5z"/><path d="M6 12v5c3 3 9 3 12 0v-5"/></svg>',
    teacher: '<svg class="icon-svg" viewBox="0 0 24 24"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>',
    delete: '<svg class="icon-svg" viewBox="0 0 24 24"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg>',
  };

  let state = {
    expanded: false,
    selectedTenant: null,
    deptId: '',
    userKeyword: '',
    userPage: { current: 1, size: 10, total: 0, records: [] },
    loadingTenants: false,
    loadingUsers: false,
    loadingLogin: false,
    tenantKeyword: '',
    recentExpanded: false,
  };

  function $(id) { return document.getElementById(IDs[id]); }

  function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  }

  function debounce(fn, ms) {
    let t = 0;
    return (...args) => {
      clearTimeout(t);
      t = setTimeout(() => fn(...args), ms);
    };
  }

  function setStatus(text, kind) {
    // 统一走顶部悬浮 toast，不再占用面板内容空间
    ns.ui.toast(text, kind);
  }

  async function hasAdminToken() {
    const t = await ns.token.getToken();
    return Boolean(t.token);
  }

  function updateEnvBadge() {
    const el = $('envBadge');
    if (!el) return;
    const projectName = ns.currentProject.getName();
    el.textContent = projectName;
    // 简单启发式：名字包含"生产/正式/prod"显示红色警告
    if (projectName.match(/生产|正式|prod/i)) {
      el.className = 'badge error';
    } else if (projectName.match(/预发布|预发|pre/i)) {
      el.className = 'badge warning';
    } else {
      el.className = 'badge success';
    }
  }

  function toggleSection() {
    state.expanded = !state.expanded;
    const section = document.getElementById(IDs.section);
    section?.classList.toggle('expanded');
    if (state.expanded) {
      initIfNeeded();
      renderRecent();
    }
  }

  async function initIfNeeded() {
    const tokenOk = await hasAdminToken();
    if (!tokenOk) {
      setStatus('请先点击「API 登录」获取 admin token', 'err');
      return;
    }
    setStatus('', '');
    if (!$('tenantList').children.length && !state.tenantKeyword) {
      await loadTenants();
    }
  }

  async function loadTenants() {
    if (state.loadingTenants) return;
    state.loadingTenants = true;
    setStatus('加载租户中...', '');
    try {
      const res = await messages.sendToBackground({
        type: 'FETCH_TENANTS',
        payload: { current: 1, size: 10, keyword: state.tenantKeyword },
      });
      if (!res || !res.ok) throw new Error(res?.error || '加载租户失败');
      const page = tenantHelpers.extractPageData(res.res);
      renderTenantList(page.records);
      setStatus('', '');
    } catch (err) {
      setStatus(err.message, 'err');
    } finally {
      state.loadingTenants = false;
    }
  }

  function renderTenantList(records) {
    const list = $('tenantList');
    const empty = $('tenantEmpty');
    list.innerHTML = '';
    if (!records || !records.length) {
      list.classList.add('hidden');
      empty.classList.remove('hidden');
      return;
    }
    empty.classList.add('hidden');
    list.classList.remove('hidden');
    for (const item of records) {
      const t = tenantHelpers.normalizeTenant(item);
      const row = document.createElement('div');
      row.className = 'list-item' + (state.selectedTenant?.tenantId === t.tenantId ? ' active' : '');
      row.innerHTML =
        `<div class="list-item-content">` +
        `<div class="list-item-title">${escapeHtml(t.tenantName || '(未命名)')}</div>` +
        `<div class="list-item-meta">${escapeHtml(t.domain || t.contactPhone || t.tenantId)}</div>` +
        `</div>`;
      row.addEventListener('click', () => selectTenant(t));
      list.appendChild(row);
    }
  }

  async function selectTenant(tenant) {
    state.selectedTenant = tenant;
    state.deptId = '';
    state.userKeyword = '';
    state.userPage = { current: 1, size: 10, total: 0, records: [] };
    $('tenantSearch').value = tenant.tenantName || '';
    $('tenantList').innerHTML = '';
    $('tenantList').classList.add('hidden');
    $('userSearch').value = '';
    $('userList').innerHTML = '';
    $('userList').classList.add('hidden');
    $('userEmpty').classList.add('hidden');
    $('loadMore').classList.add('hidden');

    await loadUsers(true);
  }

  async function loadDepts() {
    if (!state.selectedTenant) return;
    const deptSelect = $('deptSelect');
    deptSelect.innerHTML = '<option value="">全部部门</option>';
    try {
      const res = await messages.sendToBackground({
        type: 'FETCH_DEPTS',
        payload: { tenantId: state.selectedTenant.tenantId, industry: state.selectedTenant.industry },
      });
      if (!res || !res.ok) return;
      const list = tenantHelpers.extractListData(res.res);
      for (const item of list) {
        const d = tenantHelpers.normalizeDept(item);
        const opt = document.createElement('option');
        opt.value = d.deptId;
        opt.textContent = d.deptName || d.deptId;
        deptSelect.appendChild(opt);
      }
    } catch (_) {}
  }

  async function loadUsers(reset = false) {
    if (!state.selectedTenant) return;
    if (state.loadingUsers) return;
    state.loadingUsers = true;
    if (reset) {
      state.userPage.current = 1;
      state.userPage.records = [];
      $('userList').innerHTML = '';
      $('userList').classList.add('hidden');
      $('userEmpty').classList.add('hidden');
    }
    setStatus('加载用户中...', '');
    try {
      const res = await messages.sendToBackground({
        type: 'FETCH_USERS',
        payload: {
          tenantId: state.selectedTenant.tenantId,
          deptId: state.deptId,
          industry: state.selectedTenant.industry,
          current: state.userPage.current,
          size: state.userPage.size,
          keyword: state.userKeyword,
        },
      });
      if (!res || !res.ok) throw new Error(res?.error || '加载用户失败');
      const page = tenantHelpers.extractPageData(res.res);
      state.userPage.total = page.total;
      state.userPage.records = reset ? page.records : state.userPage.records.concat(page.records);
      renderUsers(state.userPage.records, page.total);
      setStatus('', '');
    } catch (err) {
      setStatus(err.message, 'err');
    } finally {
      state.loadingUsers = false;
    }
  }

  function renderUsers(records, total) {
    const list = $('userList');
    const empty = $('userEmpty');
    const loadMore = $('loadMore');
    list.innerHTML = '';
    if (!records || !records.length) {
      list.classList.add('hidden');
      empty.classList.remove('hidden');
      loadMore.classList.add('hidden');
      return;
    }
    empty.classList.add('hidden');
    list.classList.remove('hidden');
    for (const item of records) {
      const u = tenantHelpers.normalizeUser(item);
      const row = document.createElement('div');
      row.className = 'list-item fade-in';
      const dataAttrs =
        `data-id="${escapeHtml(u.id)}" ` +
        `data-user-name="${escapeHtml(u.userName)}" ` +
        `data-user-id="${escapeHtml(u.userId)}"`;
      row.innerHTML =
        `<div class="list-item-content">` +
        `<div class="list-item-title">${escapeHtml(u.userName || '(未命名)')}${u.roleName ? `<span class="list-item-role">${escapeHtml(u.roleName)}</span>` : ''}</div>` +
        `<div class="list-item-meta">${escapeHtml(u.account || u.phone || u.deptName || u.userId)}</div>` +
        `</div>` +
        `<div class="list-item-actions">` +
        `<button class="action-btn" data-action="open" ${dataAttrs} title="直接跳转接口链接">${icons.open}</button>` +
        `<button class="action-btn" data-action="copy" ${dataAttrs} title="复制 token query">${icons.copy}</button>` +
        `<button class="action-btn" data-action="student" ${dataAttrs} title="跳转学生评价">${icons.student}</button>` +
        `<button class="action-btn primary" data-action="teacher" ${dataAttrs} title="跳转教师评价">${icons.teacher}</button>` +
        `</div>`;
      list.appendChild(row);
    }
    const hasMore = records.length < total;
    loadMore.classList.toggle('hidden', !hasMore);
  }

  function extractTokenQuery(url) {
    const idx = url.indexOf('?');
    return idx >= 0 ? url.slice(idx) : '';
  }

  function buildEvaluateUrl(url, path, localPort = '') {
    const queryIdx = url.indexOf('?');
    const query = queryIdx >= 0 ? url.slice(queryIdx) : '';

    if (localPort) {
      // 使用本地环境
      return `http://localhost:${localPort}${path}${query}`;
    } else {
      // 使用线上环境
      const base = queryIdx >= 0 ? url.slice(0, queryIdx) : url;
      const origin = base.replace(/\/+$/, '');
      return `${origin}${path}${query}`;
    }
  }

  // 直接跳转接口返回的 URL；若填写本地端口，仅替换域名，保留 path + query
  function buildDirectUrl(url, localPort = '') {
    if (!localPort) return url;
    try {
      const parsed = new URL(url);
      parsed.protocol = 'http:';
      parsed.host = `localhost:${localPort}`;
      parsed.hostname = 'localhost';
      parsed.port = String(localPort);
      return parsed.toString();
    } catch (_) {
      // 解析失败则退化为简单字符串替换
      return url.replace(/^https?:\/\/[^\/]+/, `http://localhost:${localPort}`);
    }
  }

  async function copyToClipboard(text) {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch (_) {
      return false;
    }
  }

  async function onLoginClick(e) {
    const btn = e.target.closest('.action-btn');
    if (!btn) return;
    const action = btn.dataset.action;
    const id = btn.dataset.id;
    if (!action || !id || !state.selectedTenant) return;
    if (state.loadingLogin) return;

    const row = btn.closest('.list-item');
    const groupBtns = row ? row.querySelectorAll('.action-btn') : [btn];
    const originalHtml = btn.innerHTML;

    const localPort = $('localPort') ? $('localPort').value.trim() : '';
    const env = localPort ? 'local' : 'online';

    state.loadingLogin = true;
    groupBtns.forEach((b) => (b.disabled = true));
    btn.innerHTML = '<span class="spinner"></span>';
    setStatus('正在获取登录链接...', '');

    try {
      const res = await messages.sendToBackground({
        type: 'QUICK_LOGIN',
        payload: {
          tenantId: state.selectedTenant.tenantId,
          tenantName: state.selectedTenant.tenantName,
          domain: state.selectedTenant.domain,
          id,
          userName: btn.dataset.userName || '',
          industry: state.selectedTenant.industry,
          env,
          localPort,
        },
      });
      if (!res || !res.ok) throw new Error(res?.error || '登录失败');
      const url = res.url;
      if (!url || typeof url !== 'string') throw new Error('virtualLogin 未返回 URL');

      if (action === 'copy') {
        const query = extractTokenQuery(url);
        if (!query) throw new Error('URL 中未找到 token query');
        const ok = await copyToClipboard(query);
        setStatus(ok ? `已复制: ${query.slice(0, 50)}...` : '复制失败', ok ? 'ok' : 'err');
      } else if (action === 'open') {
        const target = buildDirectUrl(url, localPort);
        await messages.sendToBackground({ type: 'OPEN_LOGIN_URL', payload: { url: target } });
        setStatus('已打开链接', 'ok');
      } else if (action === 'student') {
        const target = buildEvaluateUrl(url, '/student-evaluate', localPort);
        await messages.sendToBackground({ type: 'OPEN_LOGIN_URL', payload: { url: target } });
        setStatus('已打开学生评价', 'ok');
      } else if (action === 'teacher') {
        const target = buildEvaluateUrl(url, '/teacher-evaluate', localPort);
        await messages.sendToBackground({ type: 'OPEN_LOGIN_URL', payload: { url: target } });
        setStatus('已打开教师评价', 'ok');
      }
      renderRecent();
    } catch (err) {
      setStatus(err.message, 'err');
    } finally {
      state.loadingLogin = false;
      groupBtns.forEach((b) => (b.disabled = false));
      btn.innerHTML = originalHtml;
    }
  }

  async function renderRecent() {
    const wrap = $('recent');
    if (!wrap) return;
    let records = [];
    try {
      const res = await messages.sendToBackground({ type: 'GET_QUICK_LOGIN_RECENT' });
      if (res && res.ok && Array.isArray(res.records)) records = res.records;
    } catch (_) {}
    wrap.innerHTML = '';
    if (!records.length) {
      wrap.innerHTML = '<div class="recent-empty">暂无最近登录</div>';
      return;
    }

    const displayLimit = state.recentExpanded ? 10 : 5;
    const displayRecords = records.slice(0, displayLimit);
    const hasMore = records.length > displayLimit;

    for (const r of displayRecords) {
      const row = document.createElement('div');
      row.className = 'recent-item fade-in';
      const time = r.at ? new Date(r.at).toLocaleString() : '';
      const dataAttrs =
        `data-tenant-id="${escapeHtml(r.tenantId || '')}" ` +
        `data-tenant-name="${escapeHtml(r.tenantName || '')}" ` +
        `data-domain="${escapeHtml(r.domain || '')}" ` +
        `data-id="${escapeHtml(r.id || '')}" ` +
        `data-user-name="${escapeHtml(r.userName || '')}" ` +
        `data-industry="${escapeHtml(r.industry || '')}" ` +
        `data-env="${escapeHtml(r.env || 'online')}" ` +
        `data-local-port="${escapeHtml(r.localPort || '')}"`;
      const isLocal = r.env === 'local';
      const envBadge = isLocal
        ? `<span class="recent-env-badge local" title="本地端口 ${escapeHtml(r.localPort || '')}">本地${r.localPort ? ' :' + escapeHtml(r.localPort) : ''}</span>`
        : `<span class="recent-env-badge online">线上</span>`;
      row.innerHTML =
        `<div class="recent-item-info">` +
        `<div class="recent-item-text">${envBadge}${escapeHtml(r.tenantName || '(未知租户)')} · ${escapeHtml(r.userName || r.id)}</div>` +
        `<div class="recent-item-time">${escapeHtml(time)}</div>` +
        `</div>` +
        `<div class="recent-item-actions">` +
        `<button class="recent-action-btn" data-action="open" ${dataAttrs} title="直接跳转接口链接">${icons.open}</button>` +
        `<button class="recent-action-btn" data-action="copy" ${dataAttrs} title="复制 token">${icons.copy}</button>` +
        `<button class="recent-action-btn" data-action="student" ${dataAttrs} title="学生评价">${icons.student}</button>` +
        `<button class="recent-action-btn" data-action="teacher" ${dataAttrs} title="教师评价">${icons.teacher}</button>` +
        `<button class="recent-action-btn danger" data-action="delete" ${dataAttrs} title="删除记录">${icons.delete}</button>` +
        `</div>`;
      wrap.appendChild(row);
    }

    if (hasMore) {
      const expandBtn = document.createElement('button');
      expandBtn.className = 'load-more';
      expandBtn.textContent = state.recentExpanded ? '收起' : `显示更多 (${records.length - displayLimit} 条)`;
      expandBtn.addEventListener('click', () => {
        state.recentExpanded = !state.recentExpanded;
        renderRecent();
      });
      wrap.appendChild(expandBtn);
    }
  }

  async function onRecentClick(e) {
    const btn = e.target.closest('.recent-action-btn');
    if (!btn) return;
    const action = btn.dataset.action;
    const tenantId = btn.dataset.tenantId;
    const tenantName = btn.dataset.tenantName || '';
    const domain = btn.dataset.domain || '';
    const id = btn.dataset.id;
    const userName = btn.dataset.userName || '';
    const industry = btn.dataset.industry || '';
    const recordEnv = btn.dataset.env || 'online';
    const recordLocalPort = btn.dataset.localPort || '';
    if (!action) return;

    if (action === 'delete') {
      if (state.loadingLogin) return;
      try {
        await messages.sendToBackground({
          type: 'DELETE_QUICK_LOGIN_RECENT',
          payload: { tenantId, id },
        });
        setStatus('已删除', 'ok');
        renderRecent();
      } catch (err) {
        setStatus(`删除失败: ${err.message}`, 'err');
      }
      return;
    }

    if (!id || !tenantId) return;
    if (state.loadingLogin) return;

    const row = btn.closest('.recent-item');
    const groupBtns = row ? row.querySelectorAll('.recent-action-btn') : [btn];
    const originalHtml = btn.innerHTML;

    state.loadingLogin = true;
    groupBtns.forEach((b) => (b.disabled = true));
    btn.innerHTML = '<span class="spinner"></span>';
    setStatus('正在获取登录链接...', '');

    try {
      const res = await messages.sendToBackground({
        type: 'QUICK_LOGIN',
        payload: { tenantId, tenantName, domain, id, userName, industry, env: recordEnv, localPort: recordLocalPort },
      });
      if (!res || !res.ok) throw new Error(res?.error || '登录失败');
      const url = res.url;
      if (!url || typeof url !== 'string') throw new Error('virtualLogin 未返回 URL');

      if (action === 'copy') {
        const query = extractTokenQuery(url);
        if (!query) throw new Error('URL 中未找到 token query');
        const ok = await copyToClipboard(query);
        setStatus(ok ? `已复制: ${query.slice(0, 50)}...` : '复制失败', ok ? 'ok' : 'err');
      } else if (action === 'open') {
        const target = buildDirectUrl(url, recordLocalPort);
        await messages.sendToBackground({ type: 'OPEN_LOGIN_URL', payload: { url: target } });
        setStatus('已打开链接', 'ok');
      } else if (action === 'student') {
        const target = buildEvaluateUrl(url, '/student-evaluate', recordLocalPort);
        await messages.sendToBackground({ type: 'OPEN_LOGIN_URL', payload: { url: target } });
        setStatus('已打开学生评价', 'ok');
      } else if (action === 'teacher') {
        const target = buildEvaluateUrl(url, '/teacher-evaluate', recordLocalPort);
        await messages.sendToBackground({ type: 'OPEN_LOGIN_URL', payload: { url: target } });
        setStatus('已打开教师评价', 'ok');
      }
      renderRecent();
    } catch (err) {
      setStatus(err.message, 'err');
    } finally {
      state.loadingLogin = false;
      groupBtns.forEach((b) => (b.disabled = false));
      btn.innerHTML = originalHtml;
    }
  }

  function bindEvents() {
    $('header').addEventListener('click', toggleSection);

    const tenantSearch = $('tenantSearch');
    tenantSearch.addEventListener('input', debounce(() => {
      state.tenantKeyword = tenantSearch.value.trim();
      loadTenants();
    }, 300));

    $('deptSelect').addEventListener('change', (e) => {
      state.deptId = e.target.value;
      loadUsers(true);
    });

    const userSearch = $('userSearch');
    userSearch.addEventListener('input', debounce(() => {
      state.userKeyword = userSearch.value.trim();
      loadUsers(true);
    }, 300));

    $('userList').addEventListener('click', onLoginClick);

    $('loadMore').addEventListener('click', () => {
      state.userPage.current += 1;
      loadUsers(false);
    });

    $('recent').addEventListener('click', onRecentClick);
  }

  async function autoSelectFirstRecent() {
    try {
      const res = await messages.sendToBackground({ type: 'GET_QUICK_LOGIN_RECENT' });
      if (!res || !res.ok || !Array.isArray(res.records) || !res.records.length) return;
      const first = res.records[0];
      if (!first.tenantId || !first.id) return;

      // 自动填充租户搜索框并触发租户查询
      $('tenantSearch').value = first.tenantName || '';
      state.tenantKeyword = first.tenantName || '';

      // 模拟选中该租户（构造 tenant 对象）
      const tenant = {
        tenantId: first.tenantId,
        tenantName: first.tenantName || '',
        domain: first.domain || '',
        industry: first.industry || '',
      };

      state.selectedTenant = tenant;
      state.deptId = '';
      state.userKeyword = first.userName || '';
      state.userPage = { current: 1, size: 10, total: 0, records: [] };

      // 填充用户搜索框
      $('userSearch').value = first.userName || '';

      // 加载该租户下的用户列表
      await loadUsers(true);
    } catch (err) {
      console.error('自动选中最近登录失败:', err);
    }
  }

  async function init() {
    const section = document.getElementById(IDs.section);
    updateEnvBadge();
    bindEvents();
    // 默认展开快捷登录面板
    state.expanded = true;
    section?.classList.add('expanded');
    await renderRecent();
    await autoSelectFirstRecent();
  }

  ns.quickLoginUi = { init };
})();


/* ===== src/popup/other-login-ui.js ===== */
/* 内部开发工具箱 — Popup「其它」站点登录 UI（知雀） */
(() => {
  'use strict';

  const ns = globalThis.InternalDevToolkit;
  const messages = ns.messages;

  const IDs = {
    siteUrl: 'otherSiteUrl',
    account: 'otherAccount',
    password: 'otherPassword',
    pwdToggle: 'otherPwdToggle',
    loginBtn: 'otherLoginBtn',
    enterBtn: 'otherEnterBtn',
    zhiqueBtn: 'otherZhiqueBtn',
    tokenWrap: 'otherTokenWrap',
    tokenValue: 'otherTokenValue',
    tokenUpdated: 'otherTokenUpdated',
    copyTokenBtn: 'otherCopyTokenBtn',
    userMeta: 'otherUserMeta',
    history: 'otherHistoryList',
    teacherList: 'otherTeacherList',
    teacherEmpty: 'otherTeacherEmpty',
    teacherLoadMore: 'otherTeacherLoadMore',
    teacherRefreshBtn: 'otherTeacherRefreshBtn',
  };

  const icons = {
    enter: '<svg class="icon-svg" viewBox="0 0 24 24"><path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"/><polyline points="10 17 15 12 10 7"/><line x1="15" y1="12" x2="3" y2="12"/></svg>',
    zhique: '<svg class="icon-svg" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><path d="M2 12h20"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>',
    delete: '<svg class="icon-svg" viewBox="0 0 24 24"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg>',
  };

  const DEFAULT_TEACHER_PASSWORD = 'Xx@123456';
  const TEACHER_PAGE_SIZE = 10;

  let lastSavedToken = '';
  let loading = false;
  let historyExpanded = false;
  let teacherLoading = false;
  let teacherState = {
    records: [],
    total: 0,
    current: 0,
    size: TEACHER_PAGE_SIZE,
    siteUrl: '',
    defaultPassword: DEFAULT_TEACHER_PASSWORD,
  };

  function $(id) {
    return document.getElementById(IDs[id] || id);
  }

  function escapeHtml(s) {
    return String(s ?? '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  function setStatus(text, kind) {
    ns.ui.toast(text, kind);
  }

  function fillForm(form = {}) {
    if ($('siteUrl') && form.siteUrl != null) $('siteUrl').value = form.siteUrl;
    if ($('account') && form.account != null) $('account').value = form.account;
    if ($('password') && form.password != null) $('password').value = form.password;
  }

  function getEditableText(el) {
    return (el.textContent || '').replace(/ /g, ' ');
  }

  function setEditableText(el, text) {
    el.textContent = text || '';
  }

  function syncEditableState(el, wrap, text) {
    const isEmpty = !text;
    el.classList.toggle('empty', isEmpty);
    wrap.classList.toggle('empty', isEmpty);
  }

  function readForm() {
    return {
      siteUrl: ($('siteUrl')?.value || '').trim(),
      account: ($('account')?.value || '').trim(),
      password: $('password')?.value || '',
    };
  }

  function validateForm() {
    const form = readForm();
    if (!form.siteUrl) {
      setStatus('请输入网站地址', 'err');
      return null;
    }
    if (!form.account || !form.password) {
      setStatus('请输入账号和密码', 'err');
      return null;
    }
    return form;
  }

  function setButtonsLoading(active, focus = '') {
    loading = active;
    const loginBtn = $('loginBtn');
    const enterBtn = $('enterBtn');
    const zhiqueBtn = $('zhiqueBtn');
    const labels = {
      login: '登录',
      enter: '一键登入',
      zhique: '知雀',
    };
    const loadingLabels = {
      login: '登录中...',
      enter: '登入中...',
      zhique: '跳转中...',
    };

    [loginBtn, enterBtn, zhiqueBtn].forEach((btn) => {
      if (btn) btn.disabled = active;
    });

    if (loginBtn) loginBtn.textContent = active && focus === 'login' ? loadingLabels.login : labels.login;
    if (enterBtn) enterBtn.textContent = active && focus === 'enter' ? loadingLabels.enter : labels.enter;
    if (zhiqueBtn) zhiqueBtn.textContent = active && focus === 'zhique' ? loadingLabels.zhique : labels.zhique;
  }

  async function renderCredentials() {
    try {
      const res = await messages.sendToBackground({ type: 'OTHER_GET_CREDENTIALS' });
      if (!res || !res.ok) return;
      if ($('siteUrl')) $('siteUrl').value = res.siteUrl || '';
      if ($('account')) $('account').value = res.account || '';
      if ($('password')) $('password').value = res.password || '';
    } catch (_) {}
  }

  async function renderToken() {
    const tokenEl = $('tokenValue');
    const tokenWrap = $('tokenWrap');
    if (!tokenEl || !tokenWrap) return;

    let tokenState = { token: '', updatedAt: 0, user: null };
    try {
      const res = await messages.sendToBackground({ type: 'OTHER_GET_TOKEN' });
      if (res && res.ok) {
        tokenState = {
          token: res.token || '',
          updatedAt: res.updatedAt || 0,
          user: res.user || null,
        };
      }
    } catch (_) {}

    lastSavedToken = tokenState.token || '';
    if (document.activeElement !== tokenEl) {
      setEditableText(tokenEl, lastSavedToken);
    }
    syncEditableState(tokenEl, tokenWrap, lastSavedToken);

    const updatedEl = $('tokenUpdated');
    const copyBtn = $('copyTokenBtn');
    if (lastSavedToken) {
      const updatedAt = tokenState.updatedAt
        ? new Date(tokenState.updatedAt).toLocaleString()
        : '未知';
      if (updatedEl) updatedEl.textContent = `获取时间: ${updatedAt}`;
      if (copyBtn) copyBtn.disabled = false;
    } else {
      if (updatedEl) updatedEl.textContent = '';
      if (copyBtn) copyBtn.disabled = true;
    }

    const metaEl = $('userMeta');
    if (metaEl) {
      const u = tokenState.user;
      if (u && (u.username || u.account || u.tenantName)) {
        const parts = [
          u.username || u.account || '',
          u.tenantName || '',
          Array.isArray(u.roleNames) && u.roleNames.length ? u.roleNames.join('/') : '',
        ].filter(Boolean);
        metaEl.textContent = parts.join(' · ');
        metaEl.classList.remove('hidden');
      } else {
        metaEl.textContent = '';
        metaEl.classList.add('hidden');
      }
    }
  }

  async function onTokenBlur() {
    const tokenEl = $('tokenValue');
    if (!tokenEl) return;
    const next = getEditableText(tokenEl).trim();
    if (next === lastSavedToken) {
      await renderToken();
      return;
    }
    try {
      if (!next) {
        await messages.sendToBackground({ type: 'OTHER_CLEAR_TOKEN' });
        setStatus('Token 已清除', 'ok');
      } else {
        await messages.sendToBackground({
          type: 'OTHER_SAVE_TOKEN',
          payload: { token: next },
        });
        setStatus('Token 已保存', 'ok');
      }
      await renderToken();
    } catch (err) {
      setStatus(`保存失败: ${err.message}`, 'err');
    }
  }

  async function handleLoginOnly() {
    if (loading) return;
    const form = validateForm();
    if (!form) return;

    setButtonsLoading(true, 'login');
    setStatus('正在获取 token...', '');
    try {
      const res = await messages.sendToBackground({
        type: 'OTHER_LOGIN',
        payload: form,
      });
      if (!res || !res.ok) throw new Error(res?.error || '登录失败');
      if (res.siteUrl && $('siteUrl')) $('siteUrl').value = res.siteUrl;
      await renderToken();
      if (res.needResetPassword) {
        setStatus('登录成功，但该账号需要修改密码', 'err');
        return;
      }
      const name = res.user?.username || res.user?.account || '';
      setStatus(name ? `登录成功：${name}` : '登录成功，token 已保存', 'ok');
      await loadTeachers(true);
    } catch (err) {
      setStatus(`登录失败: ${err.message}`, 'err');
    } finally {
      setButtonsLoading(false);
    }
  }

  async function handleEnter(formOverride) {
    if (loading) return;
    const form = formOverride || validateForm();
    if (!form) return;

    setButtonsLoading(true, 'enter');
    setStatus('正在获取 token 并进入系统...', '');
    try {
      const res = await messages.sendToBackground({
        type: 'OTHER_ENTER',
        payload: form,
      });
      // 即使失败也可能已拿到 token（例如需改密），刷新展示
      await renderToken();
      if (!res || !res.ok) throw new Error(res?.error || '一键登入失败');
      if (res.siteUrl) fillForm({ siteUrl: res.siteUrl, account: form.account, password: form.password });
      const name = res.user?.username || res.user?.account || '';
      setStatus(name ? `已登入：${name}` : '已获取 token 并打开系统', 'ok');
      await renderHistory();
      await loadTeachers(true);
    } catch (err) {
      await renderToken();
      setStatus(err.message || '一键登入失败', 'err');
    } finally {
      setButtonsLoading(false);
    }
  }

  // 对齐教师端「AI数字课」：登录 → zhique/redirectUrl → OAuth SSO → a.zhique.cn/home
  async function handleZhiqueEnter(formOverride) {
    if (loading) return;
    const form = formOverride || validateForm();
    if (!form) return;

    setButtonsLoading(true, 'zhique');
    setStatus('正在登录并跳转知雀...', '');
    try {
      const res = await messages.sendToBackground({
        type: 'OTHER_ZHIQUE_ENTER',
        payload: form,
      });
      await renderToken();
      if (!res || !res.ok) throw new Error(res?.error || '知雀跳转失败');
      if (res.siteUrl) fillForm({ siteUrl: res.siteUrl, account: form.account, password: form.password });
      const name = res.user?.username || res.user?.account || '';
      setStatus(name ? `已跳转知雀：${name}` : '已打开知雀 SSO 链接', 'ok');
      await renderHistory();
      await loadTeachers(true);
    } catch (err) {
      await renderToken();
      setStatus(err.message || '知雀跳转失败', 'err');
    } finally {
      setButtonsLoading(false);
    }
  }

  async function renderHistory() {
    const wrap = $('history');
    if (!wrap) return;

    let records = [];
    try {
      const res = await messages.sendToBackground({ type: 'OTHER_GET_HISTORY' });
      if (res && res.ok && Array.isArray(res.records)) records = res.records;
    } catch (_) {}

    wrap.innerHTML = '';
    if (!records.length) {
      wrap.innerHTML = '<div class="recent-empty">暂无历史记录</div>';
      return;
    }

    const displayLimit = historyExpanded ? 20 : 5;
    const displayRecords = records.slice(0, displayLimit);
    const hasMore = records.length > displayLimit;

    for (const r of displayRecords) {
      const row = document.createElement('div');
      row.className = 'recent-item fade-in';
      const time = r.at ? new Date(r.at).toLocaleString() : '';
      const titleName = r.username || r.account || '(未知账号)';
      const tenant = r.tenantName || '';
      const actionBadge = r.lastAction === 'zhique'
        ? '<span class="recent-env-badge online" title="最近操作：知雀">知雀</span>'
        : '<span class="recent-env-badge local" title="最近操作：一键登入">登入</span>';
      const dataAttrs =
        `data-site-url="${escapeHtml(r.siteUrl || '')}" ` +
        `data-account="${escapeHtml(r.account || '')}"`;

      row.innerHTML =
        `<div class="recent-item-info">` +
        `<div class="recent-item-text">${actionBadge}${escapeHtml(titleName)}${tenant ? ` · ${escapeHtml(tenant)}` : ''}</div>` +
        `<div class="recent-item-time">${escapeHtml(r.account || '')}${time ? ` · ${escapeHtml(time)}` : ''}</div>` +
        `</div>` +
        `<div class="recent-item-actions">` +
        `<button class="recent-action-btn" data-action="enter" ${dataAttrs} title="一键登入">${icons.enter}</button>` +
        `<button class="recent-action-btn" data-action="zhique" ${dataAttrs} title="知雀">${icons.zhique}</button>` +
        `<button class="recent-action-btn danger" data-action="delete" ${dataAttrs} title="删除记录">${icons.delete}</button>` +
        `</div>`;
      wrap.appendChild(row);
    }

    if (hasMore || historyExpanded) {
      const expandBtn = document.createElement('button');
      expandBtn.className = 'load-more';
      expandBtn.textContent = historyExpanded
        ? '收起'
        : `显示更多 (${records.length - displayLimit} 条)`;
      expandBtn.addEventListener('click', () => {
        historyExpanded = !historyExpanded;
        renderHistory();
      });
      wrap.appendChild(expandBtn);
    }
  }

  async function findHistoryRecord(siteUrl, account) {
    try {
      const res = await messages.sendToBackground({ type: 'OTHER_GET_HISTORY' });
      const records = res && res.ok && Array.isArray(res.records) ? res.records : [];
      return records.find((r) =>
        (r.siteUrl || '') === siteUrl && (r.account || '') === account
      ) || null;
    } catch (_) {
      return null;
    }
  }

  async function onHistoryClick(e) {
    const btn = e.target.closest('.recent-action-btn');
    if (!btn) return;

    const action = btn.dataset.action;
    const siteUrl = btn.dataset.siteUrl || '';
    const account = btn.dataset.account || '';
    if (!action) return;

    if (action === 'delete') {
      if (loading) return;
      try {
        await messages.sendToBackground({
          type: 'OTHER_DELETE_HISTORY',
          payload: { siteUrl, account },
        });
        setStatus('已删除历史记录', 'ok');
        await renderHistory();
      } catch (err) {
        setStatus(`删除失败: ${err.message}`, 'err');
      }
      return;
    }

    if (!account) {
      setStatus('历史记录缺少账号', 'err');
      return;
    }
    if (loading) return;

    const record = await findHistoryRecord(siteUrl, account);
    if (!record?.password) {
      setStatus('历史记录缺少密码，请重新填写后登录', 'err');
      if (record) fillForm({ siteUrl: record.siteUrl, account: record.account, password: '' });
      return;
    }

    const form = {
      siteUrl: record.siteUrl || siteUrl,
      account: record.account || account,
      password: record.password,
    };
    fillForm(form);

    const row = btn.closest('.recent-item');
    const groupBtns = row ? row.querySelectorAll('.recent-action-btn') : [btn];
    const originalHtml = btn.innerHTML;
    groupBtns.forEach((b) => { b.disabled = true; });
    btn.innerHTML = '<span class="spinner"></span>';

    try {
      if (action === 'enter') {
        await handleEnter(form);
      } else if (action === 'zhique') {
        await handleZhiqueEnter(form);
      }
    } finally {
      groupBtns.forEach((b) => { b.disabled = false; });
      btn.innerHTML = originalHtml;
    }
  }

  function resetTeacherState(message = '登录后可加载教师列表') {
    teacherState = {
      records: [],
      total: 0,
      current: 0,
      size: TEACHER_PAGE_SIZE,
      siteUrl: '',
      defaultPassword: DEFAULT_TEACHER_PASSWORD,
    };
    renderTeacherList(message);
  }

  function renderTeacherList(emptyText = '暂无教师数据') {
    const list = $('teacherList');
    const empty = $('teacherEmpty');
    const loadMore = $('teacherLoadMore');
    if (!list || !empty || !loadMore) return;

    list.innerHTML = '';
    const records = teacherState.records || [];
    if (!records.length) {
      list.classList.add('hidden');
      empty.textContent = emptyText;
      empty.classList.remove('hidden');
      loadMore.classList.add('hidden');
      return;
    }

    empty.classList.add('hidden');
    list.classList.remove('hidden');

    for (const t of records) {
      const row = document.createElement('div');
      row.className = 'list-item fade-in';
      const phone = t.phone || t.account || '';
      const dataAttrs =
        `data-phone="${escapeHtml(phone)}" ` +
        `data-name="${escapeHtml(t.name || '')}"`;
      row.innerHTML =
        `<div class="list-item-content">` +
        `<div class="list-item-title">${escapeHtml(t.name || '(未命名)')}${t.roleName ? `<span class="list-item-role">${escapeHtml(t.roleName)}</span>` : ''}</div>` +
        `<div class="list-item-meta">${escapeHtml(phone || '无手机号')}</div>` +
        `</div>` +
        `<div class="list-item-actions">` +
        `<button class="action-btn primary" data-action="enter" ${dataAttrs} title="一键登入" ${phone ? '' : 'disabled'}>${icons.enter}</button>` +
        `<button class="action-btn" data-action="zhique" ${dataAttrs} title="知雀" ${phone ? '' : 'disabled'}>${icons.zhique}</button>` +
        `</div>`;
      list.appendChild(row);
    }

    const hasMore = records.length < (teacherState.total || 0);
    loadMore.classList.toggle('hidden', !hasMore);
    loadMore.disabled = teacherLoading;
    loadMore.textContent = teacherLoading ? '加载中...' : '加载更多';
  }

  async function loadTeachers(reset = false) {
    if (teacherLoading) return;

    const list = $('teacherList');
    const empty = $('teacherEmpty');
    const loadMore = $('teacherLoadMore');
    const refreshBtn = $('teacherRefreshBtn');

    teacherLoading = true;
    if (refreshBtn) refreshBtn.disabled = true;
    if (loadMore) {
      loadMore.disabled = true;
      loadMore.textContent = '加载中...';
    }

    try {
      // 无 token 时不请求，保持引导文案
      const tokenRes = await messages.sendToBackground({ type: 'OTHER_GET_TOKEN' });
      const token = tokenRes?.token || '';
      if (!token) {
        resetTeacherState('登录后可加载教师列表');
        return;
      }

      if (reset) {
        teacherState.records = [];
        teacherState.current = 0;
        teacherState.total = 0;
        if (list) {
          list.innerHTML = '';
          list.classList.add('hidden');
        }
        if (empty) {
          empty.textContent = '加载中...';
          empty.classList.remove('hidden');
        }
        if (loadMore) loadMore.classList.add('hidden');
      }

      const nextPage = reset ? 1 : (teacherState.current || 0) + 1;
      const siteUrl = ($('siteUrl')?.value || '').trim() || teacherState.siteUrl;
      const res = await messages.sendToBackground({
        type: 'OTHER_LIST_TEACHERS',
        payload: {
          siteUrl,
          current: nextPage,
          size: teacherState.size || TEACHER_PAGE_SIZE,
        },
      });
      if (!res || !res.ok) throw new Error(res?.error || '获取教师列表失败');

      const pageRecords = Array.isArray(res.records) ? res.records : [];
      teacherState = {
        records: reset ? pageRecords : teacherState.records.concat(pageRecords),
        total: Number(res.total) || 0,
        current: Number(res.current) || nextPage,
        size: Number(res.size) || TEACHER_PAGE_SIZE,
        siteUrl: res.siteUrl || siteUrl,
        defaultPassword: res.defaultPassword || DEFAULT_TEACHER_PASSWORD,
      };
      renderTeacherList(reset ? '暂无教师数据' : '暂无更多教师');
    } catch (err) {
      if (reset || !teacherState.records.length) {
        resetTeacherState(err.message || '获取教师列表失败');
      }
      setStatus(err.message || '获取教师列表失败', 'err');
    } finally {
      teacherLoading = false;
      if (refreshBtn) refreshBtn.disabled = false;
      if (loadMore) {
        const hasMore = teacherState.records.length < (teacherState.total || 0);
        loadMore.disabled = false;
        loadMore.textContent = '加载更多';
        loadMore.classList.toggle('hidden', !hasMore);
      }
    }
  }

  async function onTeacherClick(e) {
    const btn = e.target.closest('.action-btn');
    if (!btn) return;

    const action = btn.dataset.action;
    const phone = (btn.dataset.phone || '').trim();
    if (!action || !phone) {
      setStatus('该教师缺少手机号，无法登录', 'err');
      return;
    }
    if (loading) return;

    const siteUrl = ($('siteUrl')?.value || '').trim() || teacherState.siteUrl;
    const form = {
      siteUrl,
      account: phone,
      password: teacherState.defaultPassword || DEFAULT_TEACHER_PASSWORD,
    };
    fillForm(form);

    const row = btn.closest('.list-item');
    const groupBtns = row ? row.querySelectorAll('.action-btn') : [btn];
    const originalHtml = btn.innerHTML;
    groupBtns.forEach((b) => { b.disabled = true; });
    btn.innerHTML = '<span class="spinner"></span>';

    try {
      if (action === 'enter') {
        await handleEnter(form);
      } else if (action === 'zhique') {
        await handleZhiqueEnter(form);
      }
    } finally {
      groupBtns.forEach((b) => { b.disabled = false; });
      btn.innerHTML = originalHtml;
    }
  }

  function bindEvents() {
    const pwdToggle = $('pwdToggle');
    const passwordEl = $('password');
    if (pwdToggle && passwordEl) {
      pwdToggle.addEventListener('click', () => {
        const showing = passwordEl.type === 'text';
        passwordEl.type = showing ? 'password' : 'text';
        pwdToggle.textContent = showing ? '显示' : '隐藏';
      });
    }

    $('loginBtn')?.addEventListener('click', () => handleLoginOnly());
    $('enterBtn')?.addEventListener('click', () => handleEnter());
    $('zhiqueBtn')?.addEventListener('click', () => handleZhiqueEnter());
    $('history')?.addEventListener('click', onHistoryClick);
    $('teacherList')?.addEventListener('click', onTeacherClick);
    $('teacherLoadMore')?.addEventListener('click', () => loadTeachers(false));
    $('teacherRefreshBtn')?.addEventListener('click', () => loadTeachers(true));

    $('copyTokenBtn')?.addEventListener('click', async () => {
      try {
        const res = await messages.sendToBackground({ type: 'OTHER_GET_TOKEN' });
        const token = res?.token || '';
        if (!token) {
          setStatus('暂无 Token', 'err');
          return;
        }
        await navigator.clipboard.writeText(token);
        setStatus('Token 已复制', 'ok');
      } catch (err) {
        setStatus(`复制失败: ${err.message}`, 'err');
      }
    });

    const tokenEl = $('tokenValue');
    const tokenWrap = $('tokenWrap');
    if (tokenEl && tokenWrap) {
      tokenEl.addEventListener('input', () => {
        syncEditableState(tokenEl, tokenWrap, getEditableText(tokenEl).trim());
      });
      tokenEl.addEventListener('blur', onTokenBlur);
    }
  }

  async function init() {
    bindEvents();
    await renderCredentials();
    await renderToken();
    await renderHistory();
    // 已有 token 时自动拉教师列表
    await loadTeachers(true);
  }

  ns.otherLoginUi = {
    init,
    renderToken,
    renderCredentials,
    renderHistory,
    loadTeachers,
  };
})();


/* ===== src/popup/index.js ===== */
/* 内部开发工具箱 — Popup 入口 */
(() => {
  'use strict';

  const ns = globalThis.InternalDevToolkit;
  const $ = (id) => document.getElementById(id);

  async function renderCredentials() {
    const creds = await ns.credentials.getCredentials();
    $('account').value = creds.account || '';
    $('password').value = creds.password || '';
  }

  // 记录最近一次从存储读到的 token，用于 blur 时判断用户是否改动了内容
  let lastSavedToken = '';
  // 记录最近一次从存储读到的自定义域名覆盖；空串表示未覆盖（使用项目默认）
  let lastSavedDomain = '';

  function getEditableText(el) {
    return (el.textContent || '').replace(/ /g, ' ');
  }

  function setEditableText(el, text) {
    el.textContent = text || '';
  }

  function syncEditableState(el, wrap, text) {
    const isEmpty = !text;
    el.classList.toggle('empty', isEmpty);
    wrap.classList.toggle('empty', isEmpty);
  }

  async function renderToken() {
    const tokenState = await ns.token.getToken();
    const tokenEl = $('tokenValue');
    const tokenWrap = $('tokenWrap');
    lastSavedToken = tokenState.token || '';

    // 仅在编辑区未聚焦时刷新内容，避免覆盖用户正在编辑的输入
    if (document.activeElement !== tokenEl) {
      setEditableText(tokenEl, lastSavedToken);
    }
    syncEditableState(tokenEl, tokenWrap, lastSavedToken);
    if (lastSavedToken) {
      const updatedAt = tokenState.updatedAt ? new Date(tokenState.updatedAt).toLocaleString() : '未知';
      $('tokenUpdated').textContent = `获取时间: ${updatedAt}`;
      $('copyTokenBtn').disabled = false;
    } else {
      $('tokenUpdated').textContent = '';
      $('copyTokenBtn').disabled = true;
    }
  }

  // 点击即编辑、失焦自动保存并注入：
  // 可编辑内容区会随内容自然增高，无需 textarea 与显式「编辑/保存」按钮。
  async function onTokenBlur() {
    const tokenEl = $('tokenValue');
    const next = getEditableText(tokenEl).trim();
    // 内容未变化，仅刷新显示态
    if (next === lastSavedToken) {
      await renderToken();
      return;
    }
    if (!next) {
      // 清空了 token
      try {
        await ns.token.clearToken();
        await renderToken();
        setLoginStatus('Token 已清除', 'ok');
        ns.messages.sendToActiveTab({ type: 'CLEAR_TOKEN' }).catch(() => {});
      } catch (err) {
        setLoginStatus(`清除失败: ${err.message}`, 'err');
      }
      return;
    }
    try {
      await ns.token.saveToken(next);
      await renderToken();
      setLoginStatus('Token 已保存并注入页面', 'ok');
      // 立即向当前标签页注入新 token（与 API 登录成功后行为一致）
      ns.messages.sendToActiveTab({ type: 'INJECT_TOKEN' }).catch(() => {});
    } catch (err) {
      setLoginStatus(`保存失败: ${err.message}`, 'err');
    }
  }

  // 项目默认 baseUrl，用于「无覆盖」时回填输入框与判断是否回到默认
  function getDefaultBaseUrl() {
    return ns.currentProject.getProject().baseUrl || '';
  }

  async function renderDomain() {
    const domainState = await ns.customDomain.getDomain();
    const domainEl = $('domainValue');
    const domainWrap = $('domainWrap');
    const defaultUrl = getDefaultBaseUrl();
    lastSavedDomain = domainState.baseUrl || '';

    // 显示当前生效地址：有覆盖用覆盖，否则回填默认值便于在其基础上修改
    const effective = lastSavedDomain || defaultUrl;
    if (document.activeElement !== domainEl) {
      setEditableText(domainEl, effective);
    }
    syncEditableState(domainEl, domainWrap, effective);
    if (effective) {
      if (lastSavedDomain) {
        const updatedAt = domainState.updatedAt ? new Date(domainState.updatedAt).toLocaleString() : '未知';
        $('domainUpdated').textContent = `自定义 · 更新于 ${updatedAt}`;
      } else {
        $('domainUpdated').textContent = defaultUrl ? `项目默认 · ${defaultUrl}` : '';
      }
      $('copyDomainBtn').disabled = false;
    } else {
      $('domainUpdated').textContent = '';
      $('copyDomainBtn').disabled = true;
    }
    // 提示当前默认域名（便于用户参考）
    const hint = $('domainDefaultHint');
    if (hint) hint.textContent = defaultUrl;
  }

  // 点击即编辑、失焦自动保存：与 token 交互一致。
  // 清空或填回默认值 → 清除覆盖（恢复默认）；填入新值 → 保存覆盖并通知 background 刷新缓存。
  async function onDomainBlur() {
    const domainEl = $('domainValue');
    const next = getEditableText(domainEl).trim();
    const defaultUrl = getDefaultBaseUrl();

    // 视为「未覆盖」的两种情况：空串 / 等于默认值
    const isDefault = !next || next === defaultUrl;
    const normalizedNext = isDefault ? '' : next;

    if (normalizedNext === lastSavedDomain) {
      // 内容未实质变化，仅刷新显示态
      await renderDomain();
      return;
    }
    try {
      if (normalizedNext) {
        await ns.customDomain.saveDomain(normalizedNext);
        setLoginStatus('域名已保存，后台请求将使用新地址', 'ok');
      } else {
        await ns.customDomain.clearDomain();
        setLoginStatus('已恢复项目默认域名', 'ok');
      }
      await renderDomain();
      // 通知 background 刷新内存缓存（getBaseUrl 同步读取该缓存）
      ns.messages.sendToBackground({ type: 'REFRESH_BASE_URL' }).catch(() => {});
    } catch (err) {
      setLoginStatus(`保存失败: ${err.message}`, 'err');
    }
  }

  function setLoginStatus(text, kind) {
    // 统一走顶部悬浮 toast，不再占用面板内容空间
    ns.ui.toast(text, kind);
  }

  function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, (c) => ({
      '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
    }[c]));
  }

  function bindEditableField(id, onBlur) {
    const el = $(id);
    const wrap = el?.closest('.token-shell');
    if (!el || !wrap) return;
    el.addEventListener('input', () => {
      syncEditableState(el, wrap, getEditableText(el).trim());
    });
    el.addEventListener('blur', onBlur);
  }

  async function copyToClipboard(text, successText = '内容已复制') {
    if (!text) return;
    try {
      await navigator.clipboard.writeText(text);
      setLoginStatus(successText, 'ok');
    } catch (err) {
      setLoginStatus(`复制失败: ${err.message}`, 'err');
    }
  }

  function bindCredentials() {
    $('pwdToggle').addEventListener('click', () => {
      const input = $('password');
      const showing = input.type === 'text';
      input.type = showing ? 'password' : 'text';
      $('pwdToggle').textContent = showing ? '显示' : '隐藏';
    });

    $('saveBtn').addEventListener('click', async () => {
      const account = $('account').value.trim();
      const password = $('password').value;
      if (!account || !password) {
        setLoginStatus('请输入账号和密码', 'err');
        return;
      }
      try {
        await ns.credentials.saveCredentials({ account, password });
        setLoginStatus('已保存', 'ok');
      } catch (err) {
        setLoginStatus(`保存失败: ${err.message}`, 'err');
      }
    });

    $('clearBtn').addEventListener('click', async () => {
      try {
        await ns.credentials.clearCredentials();
        await ns.token.clearToken();
        $('account').value = '';
        $('password').value = '';
        await renderToken();
        setLoginStatus('已清除', 'ok');
      } catch (err) {
        setLoginStatus(`清除失败: ${err.message}`, 'err');
      }
    });

    $('apiLoginBtn').addEventListener('click', async () => {
      const account = $('account').value.trim();
      const password = $('password').value;
      if (!account || !password) {
        setLoginStatus('请输入账号和密码', 'err');
        return;
      }

      setLoginStatus('正在登录...', '');
      try {
        await ns.credentials.saveCredentials({ account, password });
      } catch (err) {
        setLoginStatus(`保存失败: ${err.message}`, 'err');
        return;
      }

      try {
        const res = await ns.messages.sendToBackground({
          type: 'LOGIN_API',
          payload: { account, password },
        });
        if (res && res.ok) {
          await renderToken();
          setLoginStatus('登录成功，token 已保存', 'ok');
          ns.messages.sendToActiveTab({ type: 'INJECT_TOKEN' }).catch(() => {});
        } else {
          setLoginStatus(res?.error || '登录失败', 'err');
        }
      } catch (err) {
        setLoginStatus(`登录失败: ${err.message}`, 'err');
      }
    });

    $('copyTokenBtn').addEventListener('click', async () => {
      const tokenState = await ns.token.getToken();
      await copyToClipboard(tokenState.token, 'Token 已复制');
    });

    // 点击即编辑、失焦自动保存并注入（无需编辑/保存按钮）
    bindEditableField('tokenValue', onTokenBlur);

    // 域名地址：点击即编辑、失焦自动保存（与 token 交互一致）
    bindEditableField('domainValue', onDomainBlur);
    $('copyDomainBtn').addEventListener('click', async () => {
      // 复制当前生效地址（覆盖值或默认值）
      const state = await ns.customDomain.getDomain();
      const url = state.baseUrl || getDefaultBaseUrl();
      await copyToClipboard(url, '域名已复制');
    });
  }

  function bindAdminPanelToggle() {
    const section = $('adminPanelSection');
    const header = $('adminPanelHeader');
    const body = $('adminPanelBody');
    if (!section || !header || !body) return;
    header.addEventListener('click', () => {
      section.classList.toggle('expanded');
    });
  }

  // Tab 切换：原写在 popup.html 的内联 <script> 里，但 MV3 的 CSP
  // (script-src 'self') 会拦截内联脚本，导致 tab 按钮绑不上事件、切不过去。
  // 这里改由外部 popup.js 绑定，CSP 允许 'self'。
  function bindTabSwitcher() {
    const tabs = document.querySelectorAll('.tab-btn');
    const panels = {
      admin: $('panel-admin'),
      quick: $('panel-quick'),
      other: $('panel-other'),
    };
    tabs.forEach((btn) => {
      btn.addEventListener('click', () => {
        const key = btn.dataset.tab;
        if (!key || !panels[key]) return;
        tabs.forEach((t) => t.classList.remove('active'));
        btn.classList.add('active');
        Object.keys(panels).forEach((k) => {
          panels[k]?.classList.toggle('active', k === key);
        });
      });
    });
  }

  async function init() {
    // 加载当前项目
    await ns.currentProject.loadCurrentProject();

    // 初始化项目切换器
    if (ns.projectSwitcherUi) {
      await ns.projectSwitcherUi.init();
    }

    // 根据当前项目的 enabledFeatures 显示/隐藏功能卡
    const enabledFeatures = ns.currentProject.getEnabledFeatures();
    if (!enabledFeatures.includes('adminPanel')) {
      const adminPanelSection = $('adminPanelSection');
      if (adminPanelSection) adminPanelSection.style.display = 'none';
    }
    if (!enabledFeatures.includes('quickLogin')) {
      const quickLoginSection = $('quickLoginSection');
      if (quickLoginSection) quickLoginSection.style.display = 'none';
    }

    await renderCredentials();
    await renderToken();
    await renderDomain();
    bindCredentials();
    bindAdminPanelToggle();
    bindTabSwitcher();
    if (ns.quickLoginUi && enabledFeatures.includes('quickLogin')) {
      await ns.quickLoginUi.init();
    }
    if (ns.otherLoginUi) {
      await ns.otherLoginUi.init();
    }
  }

  init().catch((err) => {
    console.error('[内部开发工具箱] 初始化失败:', err);
  });
})();
