#!/usr/bin/env node
/* 内部开发工具箱 — 零依赖构建脚本 */
// ⚠️  manifest.json 由 generateManifest() 自动生成，请勿手动编辑
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const dist = path.join(root, 'dist');

// 按依赖顺序打包（公共模块在各自列表中重复包含）
// projects.js 和 current-project.js 必须在所有依赖它们的模块之前
const contentFiles = [
  'src/common/projects.js',
  'src/common/current-project.js',
  'src/common/token.js',
  'src/common/credentials.js',
  'src/common/tenant.js',
  'src/common/mock-storage.js',
  'src/common/mock-generator.js',
  'src/content/ui.js',
  'src/content/messages.js',
  'src/content/mock-interceptor.js',
  'src/content/api-proxy.js',
  'src/content/index.js',
];

const popupFiles = [
  'src/common/projects.js',
  'src/common/current-project.js',
  'src/common/credentials.js',
  'src/common/token.js',
  'src/common/custom-domain.js',
  'src/common/tenant.js',
  'src/common/quick-login-state.js',
  'src/content/messages.js',
  'src/popup/ui.js',
  'src/popup/workspace-ui.js',
  'src/popup/quick-login-ui.js',
  'src/popup/other-login-ui.js',
  'src/popup/app-login-ui.js',
  'src/popup/index.js',
];

const backgroundFiles = [
  'src/common/projects.js',
  'src/common/current-project.js',
  'src/common/credentials.js',
  'src/common/token.js',
  'src/common/custom-domain.js',
  'src/common/tenant.js',
  'src/common/mock-storage.js',
  'src/common/mock-generator.js',
  'src/background/cookies.js',
  'src/background/api.js',
  'src/background/tenant-api.js',
  'src/background/quick-login.js',
  'src/background/other-login.js',
  'src/background/app-login.js',
  'src/background/mock-handler.js',
  'src/background/index.js',
];

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function copyFile(src, dest) {
  ensureDir(path.dirname(dest));
  fs.copyFileSync(src, dest);
}

function bundle(files, banner) {
  return banner + '\n' + files.map((file) => {
    const fullPath = path.join(root, file);
    return `\n/* ===== ${file} ===== */\n` + fs.readFileSync(fullPath, 'utf8').trim() + '\n';
  }).join('\n');
}

function writeGenerated(file, content) {
  fs.writeFileSync(path.join(root, file), content);
  fs.writeFileSync(path.join(dist, file), content);
}

function generateManifest() {
  const { PROJECTS } = require(path.join(root, 'src/common/projects.js'));

  // 放开为 <all_urls>：任意页面（含 localhost 开发环境）均允许注入。
  const hostPermissions = ['<all_urls>'];
  const matches = hostPermissions;

  const manifest = {
    manifest_version: 3,
    name: '内部开发工具箱',
    version: '0.1.0',
    minimum_chrome_version: '116',
    description: '公司内部开发用浏览器插件脚手架：页面增强、浏览器侧边栏、设置持久化与消息通信示例',
    icons: {
      '16': 'icons/icon16.png',
      '48': 'icons/icon48.png',
      '128': 'icons/icon128.png'
    },
    permissions: ['activeTab', 'storage', 'scripting', 'tabs', 'cookies', 'sidePanel'],
    host_permissions: hostPermissions,
    background: {
      service_worker: 'background.js'
    },
    action: {
      default_title: '打开内部开发工具箱',
      default_icon: {
        '16': 'icons/icon16.png',
        '48': 'icons/icon48.png'
      }
    },
    side_panel: {
      default_path: 'popup.html'
    },
    devtools_page: 'devtools.html',
    content_scripts: [
      {
        matches: matches,
        js: ['content.js'],
        css: ['styles.css'],
        run_at: 'document_start'
      }
    ]
  };

  const content = JSON.stringify(manifest, null, 2);
  fs.writeFileSync(path.join(root, 'manifest.json'), content);
  fs.writeFileSync(path.join(dist, 'manifest.json'), content);
  console.log(`✓ Generated manifest.json with host_permissions: ${hostPermissions.join(', ')}`);
}

ensureDir(dist);
ensureDir(path.join(dist, 'icons'));

generateManifest();

writeGenerated('content.js', bundle(contentFiles, '/* Generated by scripts/build.js. Source: src/content/*.js */'));
writeGenerated('popup.js', bundle(popupFiles, '/* Generated by scripts/build.js. Source: src/popup/*.js */'));
writeGenerated('background.js', bundle(backgroundFiles, '/* Generated by scripts/build.js. Source: src/background/*.js */'));

// mock-hook.js 运行在页面主上下文（MAIN world），不再静态注入；
// 由 background 在「接口 Mock 总开关开启」的前提下通过 scripting.executeScript 按需注入
// （DevTools 面板激活或开关开启时触发）。仅需打包进扩展，无需 web_accessible_resources。
copyFile(path.join(root, 'src/content/mock-hook.js'), path.join(root, 'mock-hook.js'));
copyFile(path.join(root, 'src/content/mock-hook.js'), path.join(dist, 'mock-hook.js'));

for (const file of ['popup.html', 'styles.css', 'README.md']) {
  copyFile(path.join(root, file), path.join(dist, file));
}

for (const file of fs.readdirSync(path.join(root, 'icons'))) {
  copyFile(path.join(root, 'icons', file), path.join(dist, 'icons', file));
}

// Copy devtools files
const devtoolsDir = path.join(root, 'devtools');
if (fs.existsSync(devtoolsDir)) {
  ensureDir(path.join(dist, 'devtools'));
  for (const file of fs.readdirSync(devtoolsDir)) {
    // 跳过子目录（如 vendor），由下方单独递归处理
    if (fs.statSync(path.join(devtoolsDir, file)).isDirectory()) continue;
    copyFile(path.join(devtoolsDir, file), path.join(dist, 'devtools', file));
  }
}

// Copy devtools vendor libs (codejar/prism 等) 递归到 dist/devtools/vendor
const vendorDir = path.join(devtoolsDir, 'vendor');
if (fs.existsSync(vendorDir)) {
  ensureDir(path.join(dist, 'devtools', 'vendor'));
  for (const file of fs.readdirSync(vendorDir)) {
    if (fs.statSync(path.join(vendorDir, file)).isDirectory()) continue;
    copyFile(path.join(vendorDir, file), path.join(dist, 'devtools', 'vendor', file));
  }
}

// Copy devtools entry files
if (fs.existsSync(path.join(root, 'devtools.html'))) {
  copyFile(path.join(root, 'devtools.html'), path.join(dist, 'devtools.html'));
}
if (fs.existsSync(path.join(root, 'devtools.js'))) {
  copyFile(path.join(root, 'devtools.js'), path.join(dist, 'devtools.js'));
}

console.log('✅ Build complete: root generated files and dist/ are up to date.');
